definitions:
    steps:
        - step:
            name: Generic compilation
            script: &compile
                - export MAKEFLAGS=--jobs=$(nproc)
                - make clean
                - make lib libdynamiccorrection tests
                - cd examples/posix
                - make clean
                - make nosdl

pipelines:
    default:
        - parallel:
            - step:
                name: GCC 6 compilation
                image: docker.io/library/gcc:6
                script: *compile
            - step:
                name: GCC 7 compilation
                image: docker.io/library/gcc:7
                script: *compile
            - step:
                name: GCC 8 compilation
                image: docker.io/library/gcc:8
                script: *compile
            - step:
                name: GCC 9 compilation
                image: docker.io/library/gcc:9
                script: *compile
            - step:
                name: GCC 10 compilation
                image: docker.io/library/gcc:10
                script: *compile
            - step:
                name: GCC 11 compilation
                image: docker.io/library/gcc:11
                script: *compile
            - step:
                name: GCC 12 compilation
                image: docker.io/library/gcc:12
                script: *compile
            - step:
                name: GCC 13 compilation
                image: docker.io/library/gcc:13
                script: *compile
            - step:
                name: GCC 14 compilation
                image: docker.io/library/gcc:14
                script: *compile
            - step:
                name: GCC 15 compilation
                image: docker.io/library/gcc:15
                script: *compile

            # To save time, and to avoid the need to reconfigure APT to pull
            # from the Debian Archives on the older images, we'll only build
            # the SDL example on the latest version of GCC.
            - step:
                name: SDL example compilation
                image: docker.io/library/gcc:15
                script:
                    - apt-get update && apt-get -y install libsdl2-dev
                    - export MAKEFLAGS=--jobs=$(nproc)
                    - make lib
                    - cd examples/posix
                    - make posix-stream-sdl

            - step:
                name: Zephyr example compilation
                # Container version pinned to provide an SDK compatible with
                # the Zephyr version specified in west.yml.
                image: ghcr.io/zephyrproject-rtos/ci:v0.28.8
                script:
                    - cd examples/zephyr/
                    # We're in the unique position of trying to use a consume
                    # this repository as a West module from a West manifest
                    # stored within this repository. We'll rewrite the manifest
                    # so that West pulls in the expected commit.
                    - 'sed --in-place "0,/revision: .*/ { s//revision: $BITBUCKET_COMMIT/ }" application/west.yml'
                    - west init --local application/
                    - west update
                    - cd application/
                    - >-
                        boards=$(ls -1 boards/ | cut --delimiter . --field 1 | sort | uniq);
                        for board in $boards;
                        do
                            west build \
                                --board=$board \
                                --build-dir=build-$board/ \
                                -- \
                                -DEXTRA_CONF_FILE=debug.conf;
                        done

            # To save time, and under the assumption that the quality and
            # relevance of scan-build findings will only improve over time,
            # we'll perform static analysis with only the latest version of
            # Clang.
            - step:
                name: Clang 20 compilation and static analysis
                image: docker.io/silkeh/clang:20
                script:
                    - apt-get update && apt-get -y install libsdl2-dev
                    - export CC=clang CCC_CC=clang MAKEFLAGS=--jobs=$(nproc)
                    - make clean
                    - scan-build make lib libdynamiccorrection
                    - make tests
                    - cd examples/posix
                    - make clean
                    - scan-build make

            - step:
                name: Documentation compilation
                image: docker.io/library/gcc:15
                script:
                    - apt-get update && apt-get -y install doxygen graphviz
                    - make clean
                    - make docs
                    - make clean
                    - make devdocs
