@startuml

title RBRGen4

package RBRGen4 {
    class lib {
        extern const char *NAME
        extern const char *VERSION
        extern const char *BUILD_DATE
    }

    class error {
        enum SUCCESS
        enum UNDERSIZED_STRUCTURE_ERROR
        enum BUFFER_TOO_SMALL
        enum MISSING_CALLBACK
        enum CALLBACK_ERROR
        enum TIMEOUT
        enum UNSUPPORTED
        enum HARDWARE_ERROR
        enum CHECKSUM_ERROR
        enum INVALID_PARAMETER_VALUE
        enum SAMPLE
        enum COMMUNICATION_ERROR
        enum COUNT
        enum UNKNOWN 
        const char *name()
    }

    package time {
        class dateTime {
            typedef int64_t dateTime
            const uint64_t MIN
            const uint64_t MAX
            error fromSampleTime(const char *buf, char **end)
            error fromScheduleTime(const char *buf, char **end)
            error toSampleTime(char *buf)
            error toScheduleTime(char *buf)
        }
        error <-- dateTime

        class period {
            typedef int32_t period
            const uint64_t MIN
            const uint64_t MAX
        }

        class clock {
            dateTime dateTime
            float offsetFromUTC
        }
        dateTime <-- clock::dateTime
    }

    package info {
        class generation {
            enum 1
            enum 2
            enum 3
            enum 4
            enum COUNT
            enum UNKNOWN 
            const char* name()
        }

        class versionCompareResult {
            enum INVALID
            enum LESS_THAN
            enum GREATER_THAN
            enum EQUAL
        }

        class version {
            const char *version
            const char *VERSION_MIN
            uint32_t VERSION_MAX_LENGTH
            const char *VERSION_NUM_MAJOR
            const char *VERSION_NUM_MINOR
            const char *VERSION_NUM_PATCH
            uint32_t VERSION_NUM_COUNT
            versionCompareResult compare(const char *, const char *)
        }
        versionCompareResult <-- version::versionCompareResult compare(const char *, const char *)

        class id {
            const uint32_t MODEL_MAX
            const char model[MODEL_MAX]
            version version
            uint16_t fwtype
            uint32_t sn
            uint32_t pn
            bool fwlock
            generation generation
        }
        version <-- id::version
        generation <-- id::generation
    }

    package logging {
        class logType {
            enum USER
            enum INFO
            enum WARNING
            enum ERROR
            enum COUNT
            enum UNKNOWN 
            const char* name()
        }

        class logFilter {
            enum LAST
            enum INFO
            enum WARNING
            enum ERROR
            enum COUNT
            enum UNKNOWN 
            const char* name()
        }

        class log {
            dateTime timestamp
            logType logType
            const char* text
        }
        logType <-- log::logType
    }
    time.dateTime  <-- log::timestamp

    package power {
        class sourceType {
            enum USB
            enum INTERNAL
            enum EXTERNAL
            enum COUNT
            enum UNKNOWN 
            const char* name()
        }

        class source {
            sourceType sourceType 
            float voltage
        }
        sourceType <-- source::sourceType

        class battery {
            sourceType sourceType 
            const char* batteryType
            float voltage
            float capacity
            float used
        }
        sourceType <-- battery::sourceType
    }

    class channel {
        const uint32_t MAX
        const uint32_t MAX_LEN
        const uint32_t LABEL_MAX
        const uint32_t TYPE_MAX
        const uint32_t UNIT_MAX
    }

    package schedules {
        class constants {
        }
    }

    package deployments {
        class deploymentStatus {
            enum DISABLED
            enum PENDING
            enum LOGGING
            enum GATED
            enum PAUSED
            enum FINISHED
            enum STOPPED
            enum FULLANDSTOPPED
            enum FULL
            enum FAILED
            enum NOTBLANK
            enum UNKNOWN
            enum COUNT
            enum UNRECOGNIZED 
            const char* name()
        }

        class gate {
            enum NONE
            enum THRESHOLDING
            enum TWISTACTIVATED
            enum INVALID
            enum COUNT
            enum UNRECOGNIZED 
            const char* name()
        }

        class config {
            const char configLabel[LABEL_MAX+1]
        }

        class dataset {
            const char datasetLabel[LABEL_MAX+1]
        }

        class deployment {
            uint32_t AVAILABLE_FAST_PERIODS_MAX
            dateTime startTime
            dateTime endTime
            const config config
            const dataset dataset
            const deploymentStatus status
            const direction direction
            period availableFastPeriods[AVAILABLE_FAST_PERIODS_MAX]
            const gate gate
            const direction direction
            const regimes regimes
            const schedules schedules
            const bool simulation
            error pause()
            error resume()
        }
        dateTime <-- deployment::startTime
        dateTime <-- deployment::endTime
        deploymentStatus <-- deployment::status
        period <-- deployment::availableFastPeriods
        gate <--deployment::gate
        direction <-- deployment::direction
        regimes <-- deployment::regimes
        schedules <-- deployment::schedules
    }

    package internals {
        package response {
            class response {
                hardwareError error
                responseParameter parameter
                char *response
            }
            responseParameter <-- response::parameter

            class responseParameter {
                int32_t index
                char *indexValue
                char *key
                char *value
                char *nextKey
            }
        }

        class outputFormat {
            bit SERIAL
            bit scheduleLabel
            bit TIMESTAMP
            bit CRC
            outputFormat DEFAULT
            void name(char *buf)
        }

        class dataType {
            enum FLOAT32
            enum FLOAT64
            enum COUNT
            enum UNKNOWN 
            const char* name()
        }

        class callbacks {
            typedef error (*timeCallback)(const struct instrument *instrument, dateTime *time)
            typedef error (*sleepCallback)(const struct instrument *instrument, dateTime *time)
            typedef error (*readCallback)(const struct instrument *instrument, dateTime *time)
            typedef error (*writeCallback)(const struct instrument *instrument, dateTime *time)
            typedef error (*sampleCallback)(const struct instrument *instrument, dateTime *time)
            time timeCallback
            sleep sleepCallback
            read readCallback
            write writeCallback
        }
        error <-- callbacks

        package pcbas {
            class pcba {
                const char label[LABEL_MAX]
                version fw
                const char fw[FW_MAX]
                uint32_t sn
                const char pn[PN_MAX]
                uint32_t address
            }
        }

        class instrumentState {
            enum ENABLED
            enum DISABLED
            const char* name()
        }

        class instrument {
            const uint32_t COMMAND_BUFFER_MAX
            const char* SEND_COMMAND_TERMINATOR
            uint16_t SEND_COMMAND_TERMINATOR_LEN
            uint16_t SAMPLE_TIME_LEN
            uint16_t SCHEDULE_TIME_LEN
            const uint32_t RESPONSE_BUFFER_MAX
            const char* RESPONSE_TERMINATOR
            uint16_t RESPONSE_TERMINATOR_LEN
            const dateTime NO_ACTIVITY
            error RBR_TRY(op)
            callbacks callbacks
            dataType dataType
            id id
            clock clock
            deployment deployment
            instrumentState state
            power externalBattery
            power internalBattery
            power usb
            pcba pcbas[PCBA_MAX]
            char* commandBuffer
            dateTime commandTimeout
            char* responseBuffer
            response response
            outputFormat outputFormat
            char* logBuffer
            logFilter logFilter
            log lastLog
            void* userData
            error open(const callbacks *callbacks, const dateTime commandTimeout, void* userData)
            error close()
            error factoryReset()
            error enable()
            error disable()
            error resetExternalBatteryUsed()
            error resetInternalBatteryUsed()
            error reboot()
            error eraseLog()
            error fetchLog(logFilter logFilter)
            error advanceLog(log* log)
            error sendBuffer()
            error sendCommand(const char *command)
            error readResponse(bool breakOnSample, RBRGen4Sample *sample)
            error converse()
            error parseBool(bool *parameter)
            error parseFloat(float *parameter)
            error parseInt(int32_t *parameter)
            error parseResponse(responseParameter* responseParameter)
            error errorCheckResponse(char *beginning, char *end)
        }

        response.response <-- instrument::response
        instrumentState <-- instrument::state
        dataType <-- instrument::dataType
        dateTime <-- instrument::commandTimeout
        id <-- instrument::id
        clock <-- instrument::clock
        deployment <-- instrument::deployment
        callbacks <-- instrument::callbacks
        outputFormat <-- instrument::outputFormat
        logFilter <-- instrument::logFilter
        log <-- instrument::log
        battery <-- instrument::internalBattery
        battery <-- instrument::externalBattery
        source <-- instrument::usb
        error <-- instrument
    }
}

@enduml