/* This file is automatically generated. */
#include "tests.h"
TEST_LOGGER2(link);
TEST_LOGGER3(link);
TEST_LOGGER2(serial);
TEST_LOGGER3(serial);
TEST_LOGGER3(sleep);
TEST_LOGGER2(wifi);
TEST_LOGGER3(wifi);
TEST_LOGGER2(channels);
TEST_LOGGER3(channels);
TEST_LOGGER3(channel_gain_set_auto);
TEST_LOGGER3(channel_gain_set_manual);
TEST_LOGGER3(calibration_set);
TEST_LOGGER3(settings_fetchpoweroffdelay);
TEST_LOGGER3(settings_fetchpoweroffdelay_set);
TEST_LOGGER3(settings_sensorpoweralwayson);
TEST_LOGGER3(settings_sensorpoweralwayson_set);
TEST_LOGGER3(settings_castdetection);
TEST_LOGGER3(settings_castdetection_set);
TEST_LOGGER3(settings_inputtimeout);
TEST_LOGGER3(settings_inputtimeout_set);
TEST_LOGGER3(settings_atmosphere);
TEST_LOGGER3(settings_atmosphere_set);
TEST_LOGGER2(sensor);
TEST_LOGGER2(sensor_all);
TEST_LOGGER3(sensor);
TEST_LOGGER3(sensor_all);
TEST_LOGGER2(verify);
TEST_LOGGER3(verify);
TEST_LOGGER2(enable);
TEST_LOGGER3(enable);
TEST_LOGGER2(stop);
TEST_LOGGER3(disable);
TEST_LOGGER3(simulation);
TEST_LOGGER3(simulation_set);
TEST_LOGGER3(verify_pss78);
TEST_LOGGER3(verify_ascent_rate);
TEST_LOGGER3(verify_coeff_alpha_tau_ctcoeff);
TEST_LOGGER3(verify_dynamic_correction);
TEST_LOGGER3(fetch);
TEST_LOGGER2(thresholding);
TEST_LOGGER3(thresholding);
TEST_LOGGER2(thresholding_set);
TEST_LOGGER3(thresholding_set_channel_by_index);
TEST_LOGGER3(thresholding_set_channel_by_label);
TEST_LOGGER2(twistactivation);
TEST_LOGGER3(twistactivation);
TEST_LOGGER2(twistactivation_set);
TEST_LOGGER3(twistactivation_set);
TEST_LOGGER3(meminfo);
TEST_LOGGER3(meminfo_invalid_dataset);
TEST_LOGGER2(read);
TEST_LOGGER2(read_offset_mismatch);
TEST_LOGGER3(readdata);
TEST_LOGGER3(readdata_offset_mismatch);
TEST_LOGGER3(readdata_invalid_dataset);
TEST_LOGGER3(readdata_crc_failure);
TEST_LOGGER2(memformat_support);
TEST_LOGGER3(memformat_availabletypes);
TEST_LOGGER3(memformat_type);
TEST_LOGGER3(memformat_newtype);
TEST_LOGGER3(memformat_newtype_set);
TEST_LOGGER3(postprocessing);
TEST_LOGGER3(postprocessing_set);
TEST_LOGGER3(postprocessing_command);
TEST_LOGGER3(version_comparison);
TEST_LOGGER2(id);
TEST_LOGGER3(id);
TEST_LOGGER3(id_simulated);
TEST_LOGGER3(id_short);
TEST_LOGGER2(hwrev);
TEST_LOGGER3(hwrev);
TEST_LOGGER2(powerstatus);
TEST_LOGGER3(power);
TEST_LOGGER2(powerinternal);
TEST_LOGGER3(powerinternal);
TEST_LOGGER2(powerexternal);
TEST_LOGGER3(powerexternal);
TEST_LOGGER2(info);
TEST_LOGGER3(info);
TEST_LOGGER3(info_fwlock);
TEST_LOGGER2(now);
TEST_LOGGER2(now_set);
TEST_LOGGER3(clock);
TEST_LOGGER3(clock_set);
TEST_LOGGER2(sampling);
TEST_LOGGER3(sampling);
TEST_LOGGER3(sampling_set);
TEST_LOGGER2(deployment);
TEST_LOGGER3(deployment);
TEST_LOGGER3(deployment_set);
TEST_LOGGER2(permit);
TEST_LOGGER3(permit);
TEST_LOGGER3(prompt);
TEST_LOGGER3(prompt_set);
TEST_LOGGER3(confirmation);
TEST_LOGGER3(confirmation_set_on);
TEST_LOGGER3(confirmation_set_off);
TEST_LOGGER3(reboot);
TEST_LOGGER2(outputformat_channelslist);
TEST_LOGGER3(outputformat_channelslist);
TEST_LOGGER2(outputformat_labelslist);
TEST_LOGGER3(outputformat_labelslist);
TEST_LOGGER2(outputformat_support);
TEST_LOGGER3(outputformat_availabletypes);
TEST_LOGGER3(outputformat_availabletypes_caltext07);
TEST_LOGGER3(outputformat_type);
TEST_LOGGER3(streamusb);
TEST_LOGGER3(streamserial);
TEST_LOGGER2(streamserial_aux);
TEST_LOGGER2(streamserial_set_aux);
TEST_LOGGER3(streamserial_aux);
TEST_LOGGER3(streamserial_aux_invalid);
TEST_LOGGER3(streamserial_set_aux);
TEST_LOGGER3(stream_sample_parse);
TEST_LOGGER3(regimes);
TEST_LOGGER3(regimes_set);
TEST_LOGGER3(regime);
TEST_LOGGER3(regime_set);
TEST_LOGGER3(ddsampling);
TEST_LOGGER3(ddsampling_set);
TEST_PARSER(event, two_channels);
TEST_PARSER(event_with_auxiliary_data, two_channels);
TEST_PARSER(events, two_channels);
TEST_PARSER(samples, two_channels);
TEST_LOGGER2(pauseresume_error);
TEST_LOGGER2(pause_error);
TEST_LOGGER2(resume_error);
TEST_LOGGER3(pauseresume_error);
TEST_LOGGER3(pause_error);
TEST_LOGGER3(resume_error);
TEST_LOGGER3(pauseresume);
TEST_LOGGER3(pause);
TEST_LOGGER3(resume);
InstrumentTest instrumentTests[] = {
    {"link", RBRINSTRUMENT_LOGGER2, test_link_l2},
    {"serial", RBRINSTRUMENT_LOGGER2, test_serial_l2},
    {"wifi", RBRINSTRUMENT_LOGGER2, test_wifi_l2},
    {"link", RBRINSTRUMENT_LOGGER3, test_link_l3},
    {"serial", RBRINSTRUMENT_LOGGER3, test_serial_l3},
    {"sleep", RBRINSTRUMENT_LOGGER3, test_sleep_l3},
    {"wifi", RBRINSTRUMENT_LOGGER3, test_wifi_l3},
    {"channels", RBRINSTRUMENT_LOGGER2, test_channels_l2},
    {"sensor", RBRINSTRUMENT_LOGGER2, test_sensor_l2},
    {"sensor_all", RBRINSTRUMENT_LOGGER2, test_sensor_all_l2},
    {"channels", RBRINSTRUMENT_LOGGER3, test_channels_l3},
    {"channel_gain_set_auto", RBRINSTRUMENT_LOGGER3, test_channel_gain_set_auto_l3},
    {"channel_gain_set_manual", RBRINSTRUMENT_LOGGER3, test_channel_gain_set_manual_l3},
    {"calibration_set", RBRINSTRUMENT_LOGGER3, test_calibration_set_l3},
    {"settings_fetchpoweroffdelay", RBRINSTRUMENT_LOGGER3, test_settings_fetchpoweroffdelay_l3},
    {"settings_fetchpoweroffdelay_set",
     RBRINSTRUMENT_LOGGER3,
     test_settings_fetchpoweroffdelay_set_l3},
    {"settings_sensorpoweralwayson", RBRINSTRUMENT_LOGGER3, test_settings_sensorpoweralwayson_l3},
    {"settings_sensorpoweralwayson_set",
     RBRINSTRUMENT_LOGGER3,
     test_settings_sensorpoweralwayson_set_l3},
    {"settings_castdetection", RBRINSTRUMENT_LOGGER3, test_settings_castdetection_l3},
    {"settings_castdetection_set", RBRINSTRUMENT_LOGGER3, test_settings_castdetection_set_l3},
    {"settings_inputtimeout", RBRINSTRUMENT_LOGGER3, test_settings_inputtimeout_l3},
    {"settings_inputtimeout_set", RBRINSTRUMENT_LOGGER3, test_settings_inputtimeout_set_l3},
    {"settings_atmosphere", RBRINSTRUMENT_LOGGER3, test_settings_atmosphere_l3},
    {"settings_atmosphere_set", RBRINSTRUMENT_LOGGER3, test_settings_atmosphere_set_l3},
    {"sensor", RBRINSTRUMENT_LOGGER3, test_sensor_l3},
    {"sensor_all", RBRINSTRUMENT_LOGGER3, test_sensor_all_l3},
    {"verify", RBRINSTRUMENT_LOGGER2, test_verify_l2},
    {"enable", RBRINSTRUMENT_LOGGER2, test_enable_l2},
    {"stop", RBRINSTRUMENT_LOGGER2, test_stop_l2},
    {"verify", RBRINSTRUMENT_LOGGER3, test_verify_l3},
    {"enable", RBRINSTRUMENT_LOGGER3, test_enable_l3},
    {"disable", RBRINSTRUMENT_LOGGER3, test_disable_l3},
    {"simulation", RBRINSTRUMENT_LOGGER3, test_simulation_l3},
    {"simulation_set", RBRINSTRUMENT_LOGGER3, test_simulation_set_l3},
    {"verify_pss78", RBRINSTRUMENT_LOGGER3, test_verify_pss78_l3},
    {"verify_ascent_rate", RBRINSTRUMENT_LOGGER3, test_verify_ascent_rate_l3},
    {"verify_coeff_alpha_tau_ctcoeff",
     RBRINSTRUMENT_LOGGER3,
     test_verify_coeff_alpha_tau_ctcoeff_l3},
    {"verify_dynamic_correction", RBRINSTRUMENT_LOGGER3, test_verify_dynamic_correction_l3},
    {"fetch", RBRINSTRUMENT_LOGGER3, test_fetch_l3},
    {"thresholding", RBRINSTRUMENT_LOGGER2, test_thresholding_l2},
    {"thresholding_set", RBRINSTRUMENT_LOGGER2, test_thresholding_set_l2},
    {"twistactivation", RBRINSTRUMENT_LOGGER2, test_twistactivation_l2},
    {"twistactivation_set", RBRINSTRUMENT_LOGGER2, test_twistactivation_set_l2},
    {"thresholding", RBRINSTRUMENT_LOGGER3, test_thresholding_l3},
    {"thresholding_set_channel_by_index",
     RBRINSTRUMENT_LOGGER3,
     test_thresholding_set_channel_by_index_l3},
    {"thresholding_set_channel_by_label",
     RBRINSTRUMENT_LOGGER3,
     test_thresholding_set_channel_by_label_l3},
    {"twistactivation", RBRINSTRUMENT_LOGGER3, test_twistactivation_l3},
    {"twistactivation_set", RBRINSTRUMENT_LOGGER3, test_twistactivation_set_l3},
    {"read", RBRINSTRUMENT_LOGGER2, test_read_l2},
    {"read_offset_mismatch", RBRINSTRUMENT_LOGGER2, test_read_offset_mismatch_l2},
    {"memformat_support", RBRINSTRUMENT_LOGGER2, test_memformat_support_l2},
    {"meminfo", RBRINSTRUMENT_LOGGER3, test_meminfo_l3},
    {"meminfo_invalid_dataset", RBRINSTRUMENT_LOGGER3, test_meminfo_invalid_dataset_l3},
    {"readdata", RBRINSTRUMENT_LOGGER3, test_readdata_l3},
    {"readdata_offset_mismatch", RBRINSTRUMENT_LOGGER3, test_readdata_offset_mismatch_l3},
    {"readdata_invalid_dataset", RBRINSTRUMENT_LOGGER3, test_readdata_invalid_dataset_l3},
    {"readdata_crc_failure", RBRINSTRUMENT_LOGGER3, test_readdata_crc_failure_l3},
    {"memformat_availabletypes", RBRINSTRUMENT_LOGGER3, test_memformat_availabletypes_l3},
    {"memformat_type", RBRINSTRUMENT_LOGGER3, test_memformat_type_l3},
    {"memformat_newtype", RBRINSTRUMENT_LOGGER3, test_memformat_newtype_l3},
    {"memformat_newtype_set", RBRINSTRUMENT_LOGGER3, test_memformat_newtype_set_l3},
    {"postprocessing", RBRINSTRUMENT_LOGGER3, test_postprocessing_l3},
    {"postprocessing_set", RBRINSTRUMENT_LOGGER3, test_postprocessing_set_l3},
    {"postprocessing_command", RBRINSTRUMENT_LOGGER3, test_postprocessing_command_l3},
    {"id", RBRINSTRUMENT_LOGGER2, test_id_l2},
    {"hwrev", RBRINSTRUMENT_LOGGER2, test_hwrev_l2},
    {"powerstatus", RBRINSTRUMENT_LOGGER2, test_powerstatus_l2},
    {"powerinternal", RBRINSTRUMENT_LOGGER2, test_powerinternal_l2},
    {"powerexternal", RBRINSTRUMENT_LOGGER2, test_powerexternal_l2},
    {"info", RBRINSTRUMENT_LOGGER2, test_info_l2},
    {"version_comparison", RBRINSTRUMENT_LOGGER3, test_version_comparison_l3},
    {"id", RBRINSTRUMENT_LOGGER3, test_id_l3},
    {"id_simulated", RBRINSTRUMENT_LOGGER3, test_id_simulated_l3},
    {"id_short", RBRINSTRUMENT_LOGGER3, test_id_short_l3},
    {"hwrev", RBRINSTRUMENT_LOGGER3, test_hwrev_l3},
    {"power", RBRINSTRUMENT_LOGGER3, test_power_l3},
    {"powerinternal", RBRINSTRUMENT_LOGGER3, test_powerinternal_l3},
    {"powerexternal", RBRINSTRUMENT_LOGGER3, test_powerexternal_l3},
    {"info", RBRINSTRUMENT_LOGGER3, test_info_l3},
    {"info_fwlock", RBRINSTRUMENT_LOGGER3, test_info_fwlock_l3},
    {"now", RBRINSTRUMENT_LOGGER2, test_now_l2},
    {"now_set", RBRINSTRUMENT_LOGGER2, test_now_set_l2},
    {"sampling", RBRINSTRUMENT_LOGGER2, test_sampling_l2},
    {"deployment", RBRINSTRUMENT_LOGGER2, test_deployment_l2},
    {"clock", RBRINSTRUMENT_LOGGER3, test_clock_l3},
    {"clock_set", RBRINSTRUMENT_LOGGER3, test_clock_set_l3},
    {"sampling", RBRINSTRUMENT_LOGGER3, test_sampling_l3},
    {"sampling_set", RBRINSTRUMENT_LOGGER3, test_sampling_set_l3},
    {"deployment", RBRINSTRUMENT_LOGGER3, test_deployment_l3},
    {"deployment_set", RBRINSTRUMENT_LOGGER3, test_deployment_set_l3},
    {"permit", RBRINSTRUMENT_LOGGER2, test_permit_l2},
    {"permit", RBRINSTRUMENT_LOGGER3, test_permit_l3},
    {"prompt", RBRINSTRUMENT_LOGGER3, test_prompt_l3},
    {"prompt_set", RBRINSTRUMENT_LOGGER3, test_prompt_set_l3},
    {"confirmation", RBRINSTRUMENT_LOGGER3, test_confirmation_l3},
    {"confirmation_set_on", RBRINSTRUMENT_LOGGER3, test_confirmation_set_on_l3},
    {"confirmation_set_off", RBRINSTRUMENT_LOGGER3, test_confirmation_set_off_l3},
    {"reboot", RBRINSTRUMENT_LOGGER3, test_reboot_l3},
    {"outputformat_channelslist", RBRINSTRUMENT_LOGGER2, test_outputformat_channelslist_l2},
    {"outputformat_labelslist", RBRINSTRUMENT_LOGGER2, test_outputformat_labelslist_l2},
    {"outputformat_support", RBRINSTRUMENT_LOGGER2, test_outputformat_support_l2},
    {"streamserial_aux", RBRINSTRUMENT_LOGGER2, test_streamserial_aux_l2},
    {"streamserial_set_aux", RBRINSTRUMENT_LOGGER2, test_streamserial_set_aux_l2},
    {"outputformat_channelslist", RBRINSTRUMENT_LOGGER3, test_outputformat_channelslist_l3},
    {"outputformat_labelslist", RBRINSTRUMENT_LOGGER3, test_outputformat_labelslist_l3},
    {"outputformat_availabletypes", RBRINSTRUMENT_LOGGER3, test_outputformat_availabletypes_l3},
    {"outputformat_availabletypes_caltext07",
     RBRINSTRUMENT_LOGGER3,
     test_outputformat_availabletypes_caltext07_l3},
    {"outputformat_type", RBRINSTRUMENT_LOGGER3, test_outputformat_type_l3},
    {"streamusb", RBRINSTRUMENT_LOGGER3, test_streamusb_l3},
    {"streamserial", RBRINSTRUMENT_LOGGER3, test_streamserial_l3},
    {"streamserial_aux", RBRINSTRUMENT_LOGGER3, test_streamserial_aux_l3},
    {"streamserial_aux_invalid", RBRINSTRUMENT_LOGGER3, test_streamserial_aux_invalid_l3},
    {"streamserial_set_aux", RBRINSTRUMENT_LOGGER3, test_streamserial_set_aux_l3},
    {"stream_sample_parse", RBRINSTRUMENT_LOGGER3, test_stream_sample_parse_l3},
    {"regimes", RBRINSTRUMENT_LOGGER3, test_regimes_l3},
    {"regimes_set", RBRINSTRUMENT_LOGGER3, test_regimes_set_l3},
    {"regime", RBRINSTRUMENT_LOGGER3, test_regime_l3},
    {"regime_set", RBRINSTRUMENT_LOGGER3, test_regime_set_l3},
    {"ddsampling", RBRINSTRUMENT_LOGGER3, test_ddsampling_l3},
    {"ddsampling_set", RBRINSTRUMENT_LOGGER3, test_ddsampling_set_l3},
    {"pauseresume_error", RBRINSTRUMENT_LOGGER2, test_pauseresume_error_l2},
    {"pause_error", RBRINSTRUMENT_LOGGER2, test_pause_error_l2},
    {"resume_error", RBRINSTRUMENT_LOGGER2, test_resume_error_l2},
    {"pauseresume_error", RBRINSTRUMENT_LOGGER3, test_pauseresume_error_l3},
    {"pause_error", RBRINSTRUMENT_LOGGER3, test_pause_error_l3},
    {"resume_error", RBRINSTRUMENT_LOGGER3, test_resume_error_l3},
    {"pauseresume", RBRINSTRUMENT_LOGGER3, test_pauseresume_l3},
    {"pause", RBRINSTRUMENT_LOGGER3, test_pause_l3},
    {"resume", RBRINSTRUMENT_LOGGER3, test_resume_l3},
    {0}};
extern const RBRParserConfig test_two_channels_parser_config;
ParserTest parserTests[] = {{"event", &test_two_channels_parser_config, test_event_parser},
                            {"event_with_auxiliary_data",
                             &test_two_channels_parser_config,
                             test_event_with_auxiliary_data_parser},
                            {"events", &test_two_channels_parser_config, test_events_parser},
                            {"samples", &test_two_channels_parser_config, test_samples_parser},
                            {0}};
