# Copyright (c) 2025 RBR Ltd.
# SPDX-License-Identifier: Apache-2.0

# Corresponds to the -Og GCC flag.
CONFIG_DEBUG_OPTIMIZATIONS=y

# Enable debug logging for the example application's modules.
CONFIG_IO_LOG_LEVEL_DBG=y
CONFIG_MAIN_LOG_LEVEL_DBG=y
CONFIG_TIME_LOG_LEVEL_DBG=y

# Debug-log bytes read from/written to the instrument. Disabled by default even
# for debug builds because it is very noisy.
#CONFIG_TRACE_IO=y

# Use deferred logging and a larger buffer to better accommodate the higher
# volume of log messages.
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=8192
