# Copyright (c) 2025 RBR Ltd.
# SPDX-License-Identifier: Apache-2.0

# We need stack space for libRBR's internal string buffers. We could instead
# adjust RBRINSTRUMENT_COMMAND_BUFFER_MAX and RBRINSTRUMENT_RESPONSE_BUFFER_MAX
# to decrease the amount of space required.
CONFIG_MAIN_STACK_SIZE=2048

# The example uses printf to write streaming data output to the console.
CONFIG_CONSOLE=y

# The example Zephyr-to-libRBR I/O bindings use the async UART API.
CONFIG_UART_ASYNC_API=y

# On real hardware where we build against the Picolibc standard C library,
# ensure printf can print floating-point values.
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_IO_FLOAT=y

# We need libRBR, of course!
CONFIG_LIBRBR=y

# The example uses informational logging for non-sample output.
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y
