/*
 * Copyright (c) 2018 RBR Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * \file RBRGen4HardwareErrors.h
 *
 * \brief Instrument hardware errors.
 */

#ifndef LIBRBR_RBRGEN4HARDWAREERRORS_H
#define LIBRBR_RBRGEN4HARDWAREERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief Errors which can be returned by the instrument.
 */
typedef enum RBRGen4HardwareError {
    RBRGEN4_HARDWARE_ERROR_NONE = 0,
    RBRGEN4_HARDWARE_ERROR_COMMAND_PARSER_BUSY = 101,
    RBRGEN4_HARDWARE_ERROR_INVALID_COMMAND = 102,
    RBRGEN4_HARDWARE_ERROR_FEATURE_NOT_YET_IMPLEMENTED = 104,
    RBRGEN4_HARDWARE_ERROR_COMMAND_PROHIBITED_WHILE_LOGGING = 105,
    RBRGEN4_HARDWARE_ERROR_COMMAND_PROHIBITED_DURING_POLLING_PERSISTENCE_WINDOW = 106,
    RBRGEN4_HARDWARE_ERROR_EXPECTED_ARGUMENT_MISSING = 107,
    RBRGEN4_HARDWARE_ERROR_INVALID_ARGUMENT_TO_COMMAND = 108,
    RBRGEN4_HARDWARE_ERROR_FEATURE_NOT_AVAILABLE = 109,
    RBRGEN4_HARDWARE_ERROR_BUFFER_FULL = 110,
    RBRGEN4_HARDWARE_ERROR_COMMAND_FAILED = 111,
    RBRGEN4_HARDWARE_ERROR_FEATURE_NOT_SUPPORTED_BY_HARDWARE = 114,
    RBRGEN4_HARDWARE_ERROR_SYNTAX_ERROR = 115,
    RBRGEN4_HARDWARE_ERROR_PARSE_ERROR = 116,
    RBRGEN4_HARDWARE_ERROR_UNKNOWN_QUALIFIER = 117,
    RBRGEN4_HARDWARE_ERROR_INVALID_QUALIFIER = 118,
    RBRGEN4_HARDWARE_ERROR_MISSING_QUALIFIER = 119,
    RBRGEN4_HARDWARE_ERROR_LABEL_ALREADY_IN_USE = 120,
    RBRGEN4_HARDWARE_ERROR_NO_QUALIFIED_OBJECTS = 121,
    RBRGEN4_HARDWARE_ERROR_VALUE_IS_TOO_LONG = 122,
    RBRGEN4_HARDWARE_ERROR_VALUE_IS_A_KEYWORD_AND_CANNOT_BE_USED_AS_A_VALUE = 123,
    RBRGEN4_HARDWARE_ERROR_VALUE_CANNOT_BE_SET_MULTIPLE_TIMES = 124,
    RBRGEN4_HARDWARE_ERROR_PARAMETER_IS_READ_ONLY = 125,
    RBRGEN4_HARDWARE_ERROR_ARGUMENTS_RESULT_IN_AMBIGUOUS_COMMAND = 126,
    RBRGEN4_HARDWARE_ERROR_NO_VALUE_HAS_BEEN_SET = 127,
    RBRGEN4_HARDWARE_ERROR_NO_MORE_ENTRIES_ALLOWED_IN_LIST = 129,
    RBRGEN4_HARDWARE_ERROR_LABEL_IS_A_KEYWORD_AND_CANNOT_BE_USED_AS_A_LABEL = 130,
    RBRGEN4_HARDWARE_ERROR_ILLEGAL_CHARACTER_IN_LABEL = 131,
    RBRGEN4_HARDWARE_ERROR_MEMORY_ERASE_NOT_COMPLETED = 301,
    RBRGEN4_HARDWARE_ERROR_DOWNLOAD_TRACKING_FAILED = 302,
    RBRGEN4_HARDWARE_ERROR_STORAGE_ACCESS_MUST_BE_SET_TO_INSTRUMENT = 303,
    RBRGEN4_HARDWARE_ERROR_DATASET_NOT_FOUND = 304,
    RBRGEN4_HARDWARE_ERROR_STORAGE_ACCESS_ALREADY_AT_SELECTED_LOCATION = 305,
    RBRGEN4_HARDWARE_ERROR_EEPROM_MEMORY_ERROR = 306,
    RBRGEN4_HARDWARE_ERROR_STORAGE_MEDIA_ERROR = 307,
    RBRGEN4_HARDWARE_ERROR_ESTIMATED_MEMORY_USAGE_EXCEEDS_CAPACITY = 401,
    RBRGEN4_HARDWARE_ERROR_MEMORY_NOT_EMPTY_ERASE_FIRST = 402,
    RBRGEN4_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_START_TIME = 403,
    RBRGEN4_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_CURRENT_TIME = 404,
    RBRGEN4_HARDWARE_ERROR_FAILED_TO_ENABLE_FOR_LOGGING = 405,
    RBRGEN4_HARDWARE_ERROR_INSTRUMENT_WAS_ALREADY_ENABLED = 408,
    RBRGEN4_HARDWARE_ERROR_NO_SAMPLING_CHANNELS_ACTIVE = 410,
    RBRGEN4_HARDWARE_ERROR_PERIOD_NOT_VALID_FOR_SELECTED_MODE = 411,
    RBRGEN4_HARDWARE_ERROR_BURST_PARAMETERS_INCONSISTENT = 412,
    RBRGEN4_HARDWARE_ERROR_PERIOD_TOO_SHORT_FOR_SERIAL_STREAMING = 413,
    RBRGEN4_HARDWARE_ERROR_THRESHOLDING_INTERVAL_NOT_VALID = 414,
    RBRGEN4_HARDWARE_ERROR_MORE_THAN_ONE_GATING_CONDITION_IS_ENABLED = 415,
    RBRGEN4_HARDWARE_ERROR_WRONG_REGIMES_SETTING = 416,
    RBRGEN4_HARDWARE_ERROR_NO_GATING_ALLOWED_WITH_REGIMES_MODE = 417,
    RBRGEN4_HARDWARE_ERROR_CAST_DETECTION_NEEDS_A_PRESSURE_DEPTH_CHANNEL = 418,
    RBRGEN4_HARDWARE_ERROR_CALIBRATION_COEFFICIENTS_ARE_MISSING = 419,
    RBRGEN4_HARDWARE_ERROR_REQUIRED_CHANNEL_IS_TURNED_OFF = 420,
    RBRGEN4_HARDWARE_ERROR_DDSAMPLING_MODE_NEEDS_PRESSURE_CHANNEL = 421,
    RBRGEN4_HARDWARE_ERROR_WRONG_DDSAMPLING_SETTINGS = 423,
    RBRGEN4_HARDWARE_ERROR_UNABLE_TO_ESTIMATE_MEMORY_USAGE = 429,
    RBRGEN4_HARDWARE_ERROR_EMPTY_SCHEDULE_LIST_IN_CONFIGURATION = 430,
    RBRGEN4_HARDWARE_ERROR_DATASET_LIMIT_REACHED = 431,
    RBRGEN4_HARDWARE_ERROR_NO_START_TIME_SPECIFIED_FOR_GATING_BY_TIME = 433,
    RBRGEN4_HARDWARE_ERROR_STARTTIME_ACCESSIBLE_ONLY_IF_GATING_BY_TIME = 434,
    RBRGEN4_HARDWARE_ERROR_INSTRUMENT_STATE_IS_ALREADY_DISABLED = 435,
    RBRGEN4_HARDWARE_ERROR_ALREADY_ENABLED_WITH_DIFFERENT_SETTINGS = 436,
    RBRGEN4_HARDWARE_ERROR_INVALID_ARGUMENT_DATA_STORAGE_IS_NOT_AVAILABLE = 437,
    RBRGEN4_HARDWARE_ERROR_CHANNELS_ON_SENSOR_SPLIT_ACROSS_SCHEDULES = 438,
    RBRGEN4_HARDWARE_ERROR_NO_SAMPLING_GROUPS_ACTIVE_IN_SCHEDULE = 439,
    RBRGEN4_HARDWARE_ERROR_INCOMPATIBLE_PERIODS_FOR_SCHEDULES_WITH_COMMON_CHANNELS = 440,
    RBRGEN4_HARDWARE_ERROR_CONFIG_HAS_TOO_MANY_CHANNELS_SENSORS_FOR_GIVEN_SAMPLING_RATE = 441,
    RBRGEN4_HARDWARE_ERROR_CONFIG_STREAMING_TOO_MUCH_DATA_FOR_CURRENT_BAUD_RATE = 442,
    RBRGEN4_HARDWARE_ERROR_CHANNEL_IS_MISCONFIGURED = 443,
    RBRGEN4_HARDWARE_ERROR_PERIOD_TOO_SHORT_FOR_CHANNEL = 444,
    RBRGEN4_HARDWARE_ERROR_ITEM_IS_NOT_CONFIGURED = 501,
    RBRGEN4_HARDWARE_ERROR_NO_CHANNELS_CONFIGURED = 505,
    RBRGEN4_HARDWARE_ERROR_SENSOR_HAS_NO_ROOT_CHANNELS = 508,
    RBRGEN4_HARDWARE_ERROR_CHANNEL_DOES_NOT_BELONG_TO_A_PERIPHERAL = 509,
    RBRGEN4_HARDWARE_ERROR_NO_CALIBRATION_FOR_CHANNEL = 601,
    RBRGEN4_HARDWARE_ERROR_DEVICE_ERROR = 701,
    RBRGEN4_HARDWARE_ERROR_NO_DEVICES_CONFIGURED = 702,
    RBRGEN4_HARDWARE_ERROR_DEVICE_SCHEDULE_INCONSISTENT = 703,
    RBRGEN4_HARDWARE_ERROR_DEVICE_IS_NOT_ENABLED = 704,
    RBRGEN4_HARDWARE_ERROR_MULTIPLE_OPERATIONS_NOT_SUPPORTED = 705,
    RBRGEN4_HARDWARE_ERROR_DISCOVERY_INCOMPLETE = 706,
    RBRGEN4_HARDWARE_ERROR_UNSUPPORTED_INSTRUMENT = 707,
    RBRGEN4_HARDWARE_ERROR_UNSUPPORTED_FIRMWARE_VERSION = 708,
    RBRGEN4_HARDWARE_ERROR_FAILED_TO_INITIALIZE_PERIPHERAL = 709,
    RBRGEN4_HARDWARE_ERROR_PERIPHERAL_DOES_NOT_SUPPORT_PASSTHROUGH = 710,
    RBRGEN4_HARDWARE_ERROR_LEAVING_PASSTHROUGH = 711
} RBRGen4HardwareError;

/**
 * \brief Get a human-readable string name for a hardware error.
 *
 * \param [in] error the hardware error
 * \return a string name for the hardware error
 * \see RBRGen4Error_name() for a description of the format of names
 */
const char *RBRGen4HardwareError_name(RBRGen4HardwareError error);

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRGEN4HARDWAREERRORS_H */
