/**
 * \file RBRGen3Memory.h
 *
 * \brief Instrument commands and structures pertaining to memory and data
 * retrieval.
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRGEN3MEMORY_H
#define LIBRBR_RBRGEN3MEMORY_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief The maximum number of channels which can be generated by a
 * post-processing job.
 */
#define RBRGEN3_POSTPROCESSING_CHANNEL_MAX 24

/**
 * \brief Possible instrument datasets.
 *
 * As an internal implementation detail, the instrument reuses file identifiers
 * (for standard and EasyParse data), and the identifiers are non-continuous
 * (there is no dataset 3). To keep confusion to a minimum, we use those same
 * identifiers here.
 */
typedef enum RBRGen3Dataset {
    /** EasyParse events */
    RBRGEN3_DATASET_EASYPARSE_EVENTS = 0,
    /** Standard data */
    RBRGEN3_DATASET_STANDARD = 1,
    /** EasyParse sample data */
    RBRGEN3_DATASET_EASYPARSE_SAMPLE_DATA = 1,
    /** EasyParse deployment header */
    RBRGEN3_DATASET_EASYPARSE_DEPLOYMENT_HEADER = 2,
    /** Reserved for use by the instrument. Cannot be downloaded. */
    RBRGEN3_DATASET_UNKNOWN_DATASET1 = 3,
    /** Post-processing sample data */
    RBRGEN3_DATASET_POSTPROCESSING_SAMPLE_DATA = 4,
    /** The number of specific datasets. */
    RBRGEN3_DATASET_COUNT,
    /** An unknown or unrecognized dataset. */
    RBRGEN3_UNKNOWN_DATASET
} RBRGen3Dataset;

/**
 * \brief Get a human-readable string name for a dataset.
 *
 * Contrary to convention for values returned by other enum `_name` functions,
 * instances of “EasyParse” found in the names returned by this function are
 * capitalized: “EasyParse sample data” instead of “easyparse sample data”.
 * And, because the standard and EasyParse sample data datasets share an
 * identifier, “standard or EasyParse data” is returned for that value.
 *
 * \param [in] dataset the dataset
 * \return a string name for the dataset
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3Dataset_name(RBRGen3Dataset dataset);

/**
 * \brief Instrument `meminfo` command parameters.
 *
 * \see RBRGen3_getMemoryInfo()
 */
typedef struct RBRGen3MemoryInfo {
    /** \brief The index of the dataset being queried. */
    RBRGen3Dataset dataset;
    /** \brief The number of bytes being used to store data in the dataset. */
    int32_t used;
    /** \brief The number of bytes available for data storage. */
    int32_t remaining;
    /** \brief The maximum total size of the dataset in bytes. */
    int32_t size;
} RBRGen3MemoryInfo;

/**
 * \brief Get information about the usage and characteristics of data memory.
 *
 * RBRGen3MemoryInfo.dataset must be set to the index of the dataset for
 * which information is to be retrieved.
 *
 * ~~~{.c}
 * RBRGen3MemoryInfo memoryInfo;
 * memoryInfo.dataset = RBRGEN3_DATASET_STANDARD;
 * RBRGen3_getMemoryInfo(instrument, &memoryInfo);
 * ~~~
 *
 * \param [in] conn the instrument connection
 * \param [in,out] memoryInfo data memory information
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_INVALID_PARAMETER_VALUE when an invalid dataset is
 *                                                requested
 * \return #RBRGEN3_HARDWARE_ERROR if the dataset is unsupported, or another
 *                                 hardware error occurs
 */
RBRGen3Error RBRGen3_getMemoryInfo(RBRGen3 *conn, RBRGen3MemoryInfo *memoryInfo);

/**
 * \brief Instrument `readdata` command parameters.
 *
 * \see RBRGen3_readData()
 */
typedef struct RBRGen3Data {
    /** \brief The index of the dataset being queried. */
    RBRGen3Dataset dataset;
    /** \brief The amount of data read. */
    int32_t size;
    /** \brief The offset in memory of the data. */
    int32_t offset;
    /** \brief The data read from the instrument. */
    void *data;
} RBRGen3Data;

/**
 * \brief Request a chunk of binary data from instrument data memory.
 *
 * When calling RBRGen3_readData(), \a data must be populated:
 *
 * - RBRGen3Data.dataset must be the index of the dataset to read from
 * - RBRGen3Data.size must be the maximum amount of data to read
 * - RBRGen3Data.offset must be the offset in memory from which to read
 * - RBRGen3Data.data must be a pointer to a location to which the data
 *   can be written
 *
 * Upon return, \a data will have been modified so that the dataset, size, and
 * offset reflect the the instrument response. Be sure to check the reported
 * size as it may differ from the requested size, especially when the
 * instrument is busy or if you're reading the last chunk of the dataset.
 *
 * For example:
 *
 * ~~~{.c}
 * uint8_t buf[1400];
 * RBRGen3Data data = {
 *     .dataset = RBRGEN3_DATASET_STANDARD,
 *     .size    = 1400,
 *     .offset  = 2800,
 *     .data    = buf
 * };
 * RBRGen3_readData(instrument, &data);
 * fwrite(buf, data.size, 1, datasetFile);
 * ~~~
 *
 * A communication error will be reported if the offset in response doesn't match request.
 * A checksum error will be reported if the CRC check of the read data fails.
 * However, \a data will still faithfully reflect the response parameters and
 * data. Be sure to check the return value lest you accidentally consume
 * invalid/corrupt data!
 *
 * \param [in] conn the instrument connection
 * \param [in,out] data the instrument data
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_CHECKSUM_ERROR in the event of a CRC failure
 * \return #RBRGEN3_INVALID_PARAMETER_VALUE when an invalid dataset is
 *                                                requested
 * \return #RBRGEN3_HARDWARE_ERROR if the dataset is unsupported, or another
 *                                 hardware error occurs
 */
RBRGen3Error RBRGen3_readData(RBRGen3 *conn, RBRGen3Data *data);

/**
 * \brief Clear the data storage area of the flash memory.
 *
 * Currently, all datasets are erased, regardless of the data storage format in
 * use.
 *
 * \param [in] conn the instrument connection
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_HARDWARE_ERROR if the memory failed to erase, or another
 *                                 hardware error occurs
 */
RBRGen3Error RBRGen3_memoryClear(RBRGen3 *conn);

/**
 * \brief Instrument memory formats.
 *
 * \see RBRGen3_getAvailableMemoryFormats()
 * \see RBRGen3_getCurrentMemoryFormat()
 * \see RBRGen3_getNewMemoryFormat()
 * \see RBRGen3_setNewMemoryFormat()
 */
typedef enum RBRGen3MemoryFormat {
    /** No format. */
    RBRGEN3_MEMFORMAT_NONE = 0,
    /** “Standard” format, `rawbin00`. */
    RBRGEN3_MEMFORMAT_RAWBIN00 = 1 << 0,
    /** “EasyParse” format, `calbin00`. */
    RBRGEN3_MEMFORMAT_CALBIN00 = 1 << 1,
    /** Corresponds to the largest memory format enum value. */
    RBRGEN3_MEMFORMAT_MAX = RBRGEN3_MEMFORMAT_CALBIN00
} RBRGen3MemoryFormat;

/**
 * \brief Get a human-readable string name for a memory format.
 *
 * \param [in] format the memory format
 * \return a string name for the memory format
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3MemoryFormat_name(RBRGen3MemoryFormat format);

/**
 * \brief Report a list of available memory formats.
 *
 * \a memoryFormats will be treated as a bit field representation of available
 * memory formats as defined by RBRGen3MemoryFormat. For details, consult
 * the Working with Bit Fields page of the documentation.
 *
 * \param [in] conn the instrument connection
 * \param [out] memoryFormats available memory formats
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 */
RBRGen3Error RBRGen3_getAvailableMemoryFormats(RBRGen3 *conn, RBRGen3MemoryFormat *memoryFormats);

/**
 * \brief Get the current memory format.
 *
 * Retrieves the format of the data presently stored in memory, either for a
 * deployment in progress or for one which has finished. If the memory is
 * completely empty because it has been cleared, the response will be
 * #RBRGEN3_MEMFORMAT_NONE.
 *
 * \param [in] conn the instrument connection
 * \param [out] memoryFormat the current memory format
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 */
RBRGen3Error RBRGen3_getCurrentMemoryFormat(RBRGen3 *conn, RBRGen3MemoryFormat *memoryFormat);

/**
 * \brief Get the memory format to be used for the next deployment.
 *
 * \param [in] conn the instrument connection
 * \param [out] memoryFormat the new memory format
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \see RBRGen3_setNewMemoryFormat()
 */
RBRGen3Error RBRGen3_getNewMemoryFormat(RBRGen3 *conn, RBRGen3MemoryFormat *memoryFormat);

/**
 * \brief Set the memory format to be used for the next deployment.
 *
 * Hardware errors may occur if:
 *
 * - the instrument is logging
 * - you select an unavailable memory format
 *
 * \param [in] conn the instrument connection
 * \param [in] memoryFormat the new memory format
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_INVALID_PARAMETER_VALUE when an invalid format is
 *                                                requested
 * \return #RBRGEN3_HARDWARE_ERROR when the instrument is logging or if an
 *                                 unavailable memory format is selected, or
 *                                 another hardware error occurs
 * \see RBRGen3_getNewMemoryFormat()
 */
RBRGen3Error RBRGen3_setNewMemoryFormat(RBRGen3 *conn, RBRGen3MemoryFormat memoryFormat);

/**
 * \brief Functions available to aggregate channel values within bins.
 *
 * \see RBRGen3PostprocessingChannel
 */
typedef enum RBRGen3PostprocessingAggregate {
    /** average value in the bin */
    RBRGEN3_POSTPROCESSING_AGGREGATE_MEAN,
    /** standard deviation of the bin */
    RBRGEN3_POSTPROCESSING_AGGREGATE_STD,
    /** number of samples in the bin */
    RBRGEN3_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT,
    /** The number of specific post-processing aggregate functions. */
    RBRGEN3_POSTPROCESSING_AGGREGATE_COUNT,
    /** An unknown or unrecognized post-processing aggregate function. */
    RBRGEN3_UNKNOWN_POSTPROCESSING_AGGREGATE
} RBRGen3PostprocessingAggregate;

/**
 * \brief Get a human-readable string name for an aggregate function.
 *
 * For consistency with the instrument command language, returns “count”, not
 * “sample count”, for #RBRGEN3_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT.
 * The value name only includes `_SAMPLE` to disambiguate between the aggregate
 * function and the value which is the count of valid values,
 * #RBRGEN3_POSTPROCESSING_AGGREGATE_COUNT.
 *
 * \param [in] function the aggregate function
 * \return a string name for the aggregate function
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3PostprocessingAggregate_name(RBRGen3PostprocessingAggregate function);

/**
 * Post-processing channel configurations.
 *
 * \see RBRGen3Postprocessing
 */
typedef struct RBRGen3PostprocessingChannelsList {
    /** \brief The number of channels generated by post-processing. */
    int32_t count;
    /** \brief The definitions of post-processing channels. */
    struct {
        /** \brief The function used to aggregate values within bins. */
        RBRGen3PostprocessingAggregate function;
        /** \brief The label of the channel to aggregate. */
        char label[RBRGEN3_CHANNEL_LABEL_MAX + 1];
    } channels[RBRGEN3_POSTPROCESSING_CHANNEL_MAX];
} RBRGen3PostprocessingChannelsList;

/**
 * \brief Post-processing job statuses.
 *
 * \see RBRGen3Postprocessing
 */
typedef enum RBRGen3PostprocessingStatus {
    /** Post-processing is idle. */
    RBRGEN3_POSTPROCESSING_STATUS_IDLE,
    /** Post-processing is in progress. */
    RBRGEN3_POSTPROCESSING_STATUS_PROCESSING,
    /** Post-processing has completed. */
    RBRGEN3_POSTPROCESSING_STATUS_COMPLETED,
    /** Post-processing has been aborted. */
    RBRGEN3_POSTPROCESSING_STATUS_ABORTED,
    /** The number of specific post-processing statuses. */
    RBRGEN3_POSTPROCESSING_STATUS_COUNT,
    /** An unknown or unrecognized post-processing status. */
    RBRGEN3_UNKNOWN_POSTPROCESSING_STATUS
} RBRGen3PostprocessingStatus;

/**
 * \brief Get a human-readable string name for a post-processing status.
 *
 * \param [in] status the post-processing status
 * \return a string name for the post-processing status
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3PostprocessingStatus_name(RBRGen3PostprocessingStatus status);

/**
 * \brief Post-processing control commands.
 *
 * \see RBRGen3Postprocessing
 */
typedef enum RBRGen3PostprocessingCommand {
    /** Start the post-processing job. */
    RBRGEN3_POSTPROCESSING_COMMAND_START,
    /** Reset the post-processing job. */
    RBRGEN3_POSTPROCESSING_COMMAND_RESET,
    /** Abort any current post-processing job. */
    RBRGEN3_POSTPROCESSING_COMMAND_ABORT,
    /** The number of specific post-processing commands. */
    RBRGEN3_POSTPROCESSING_COMMAND_COUNT,
    /** An unknown or unrecognized post-processing command. */
    RBRGEN3_UNKNOWN_POSTPROCESSING_COMMAND
} RBRGen3PostprocessingCommand;

/**
 * \brief Get a human-readable string name for a post-processing command.
 *
 * \param [in] command the post-processing command
 * \return a string name for the post-processing command
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3PostprocessingCommand_name(RBRGen3PostprocessingCommand command);

/**
 * \brief Post-processing bin filters.
 *
 * \see RBRGen3Postprocessing
 */
typedef enum RBRGen3PostprocessingBinFilter {
    /** No filter. */
    RBRGEN3_POSTPROCESSING_BINFILTER_NONE,
    /**
     * \brief Only ascending values.
     *
     * Equivalent to ascending regimes binning. Only valid when binning by
     * depth.
     */
    RBRGEN3_POSTPROCESSING_BINFILTER_ASCENTONLY,
    /**
     * \brief Only descending values.
     *
     * Equivalent to descending regimes binning. Only valid when binning by
     * depth.
     */
    RBRGEN3_POSTPROCESSING_BINFILTER_DESCENTONLY,
    /** The number of specific post-processing bin filters. */
    RBRGEN3_POSTPROCESSING_BINFILTER_COUNT,
    /** An unknown or unrecognized post-processing bin filter. */
    RBRGEN3_UNKNOWN_POSTPROCESSING_BINFILTER
} RBRGen3PostprocessingBinFilter;

/**
 * \brief Get a human-readable string name for a post-processing bin filter.
 *
 * \param [in] filter the post-processing bin filter
 * \return a string name for the post-processing bin filter
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3PostprocessingBinFilter_name(RBRGen3PostprocessingBinFilter filter);

/**
 * \brief The instrument post-processing configuration.
 *
 * \see RBRGen3_getPostprocessing()
 * \see RBRGen3_setPostprocessing()
 */
typedef struct RBRGen3Postprocessing {
    /**
     * \brief The current state of the instrument's post-processing function.
     *
     * \readonly
     */
    RBRGen3PostprocessingStatus status;
    /**
     * \brief Post-processing statistics channel configurations.
     *
     * Functions which receive an RBRGen3Postprocessing instance will
     * expect the first RBRGen3PostprocessingChannelList.count entries to
     * be populated, and functions which return a RBRGen3Postprocessing
     * instance will similarly indicate how many entries are populated.
     */
    RBRGen3PostprocessingChannelsList channels;
    /**
     * \brief The reference channel for binning.
     *
     * If the reference is set to the keyword `tstamp`, the generated data will
     * be binned by time. Otherwise, if the reference is set to the channel
     * label of a pressure or sea pressure channel, the generated data is
     * binned by depth.
     */
    char binReference[RBRGEN3_CHANNEL_LABEL_MAX + 1];
    /** \brief How data should be filtered before binning. */
    RBRGen3PostprocessingBinFilter binFilter;
    /**
     * \brief The size of each bin.
     *
     * When binning by time: specified in milliseconds, with a precision of
     * milliseconds.
     *
     * When binning by depth: specified in decibars, with a minimum precision
     * of 0.1 dbar.
     *
     * The bin size can always be set to 0, in which case, no binning is
     * performed.
     *
     * The bin size may never be negative.
     */
    float binSize;
    /**
     * \brief The minimum timestamp value.
     *
     * All samples with an earlier timestamp are excluded from post-processing
     * input. If time binning is used, this serves as the binning origin point.
     */
    RBRGen3DateTime tstampMin;
    /**
     * \brief The maximum timestamp value.
     *
     * All samples with a later timestamp are excluded from post-processing
     * input.
     */
    RBRGen3DateTime tstampMax;
    /**
     * \brief The minimum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a lesser depth are excluded from
     * post-processing input; and unless the bin filter is set to
     * #RBRGEN3_POSTPROCESSING_BINFILTER_ASCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMin;
    /**
     * \brief The maximum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a greater depth are excluded
     * from post-processing input; and if the bin filter is set to
     * #RBRGEN3_POSTPROCESSING_BINFILTER_DESCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMax;
    /**
     * \brief (dynamic correction) Alpha parameter from Lueck and Picklo equation
     *
     * Coefficient is unitless (default 0.08)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcAlpha;
    /**
     * \brief (dynamic correction) Tau parameter from Lueck and Picklo equation (1/beta)
     *
     * Coefficient is unitless (default 8.000)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTau;
    /**
     * \brief (dynamic correction) Parameter for the time lag correction
     *          between marine temperature and conductivity cell temperature
     *
     * Coefficient is in second (default 0.35)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTdelay;
    /**
     * \brief (dynamic correction) Parameter for the long term thermal coefficient
     *                  for the conductivity cell
     *
     * Coefficient is in 1/celcius (default 2.4e-4)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcCtCoeff;
} RBRGen3Postprocessing;

/**
 * \brief Get the instrument post-processing settings.
 *
 * \param [in] conn the instrument connection
 * \param [out] postprocessing the post-processing parameters
 * \return #RBRGEN3_SUCCESS when the settings are successfully read
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_HARDWARE_ERROR when the feature is unavailable, or another
 *                                 hardware error occurs
 * \see RBRGen3_setPostprocessing()
 */
RBRGen3Error RBRGen3_getPostprocessing(RBRGen3 *conn, RBRGen3Postprocessing *postprocessing);

/**
 * \brief Set the instrument post-processing settings.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - a post-processing job is already running
 * - you set an out-of-bounds parameter the library fails to detect
 *
 * \param [in] conn the instrument connection
 * \param [in] postprocessing the post-processing parameters
 * \return #RBRGEN3_SUCCESS when the settings are successfully written
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_HARDWARE_ERROR when the settings cannot be changed, or
 *                                 another hardware error occurs
 * \return #RBRGEN3_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see RBRGen3_getPostprocessing()
 */
RBRGen3Error RBRGen3_setPostprocessing(RBRGen3 *conn, const RBRGen3Postprocessing *postprocessing);

/**
 * \brief Exercises control over the post-processing state.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - post-processing settings are invalid
 * - the wrong memory format is in use
 * - the requested reference channel is unavailable
 *
 * \param [in] conn the instrument connection
 * \param [in] command the post-processing command
 * \param [out] status the post-processing status after executing the command
 * \return #RBRGEN3_SUCCESS when the settings are successfully written
 * \return #RBRGEN3_TIMEOUT when a timeout occurs
 * \return #RBRGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRGEN3_HARDWARE_ERROR when the settings cannot be changed, or
 *                                 another hardware error occurs
 * \return #RBRGEN3_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 */
RBRGen3Error RBRGen3_setPostprocessingCommand(RBRGen3 *conn, RBRGen3PostprocessingCommand command,
                                              RBRGen3PostprocessingStatus *status);

/**
 * \brief Calculate the 16-bit CRC using the CCITT polynomial f(x)=x^16+x^12+x^5+1
 * feeding bytes into the generator LSB first and using 0xFFFF as a seed value,
 * is then transmitted.
 *
 * \param [in] data the data string used to calculate the CRC
 * \param [in] size the number of characters in the string used to calculate the CRC
 * \return calculated CRC
 */
uint16_t calculateCrc(const void *data, int32_t size);

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRGEN3MEMORY_H */
