/*
 * Copyright (c) 2018 RBR Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * \file RBRGen3HardwareErrors.h
 *
 * \brief Instrument hardware errors.
 */

#ifndef LIBRBR_RBRGEN3HARDWAREERRORS_H
#define LIBRBR_RBRGEN3HARDWAREERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief Errors which can be returned by the instrument.
 */
typedef enum RBRGen3HardwareError {
    RBRGEN3_HARDWARE_ERROR_NONE = 0,
    RBRGEN3_HARDWARE_ERROR_COMMAND_PARSER_BUSY = 101,
    RBRGEN3_HARDWARE_ERROR_INVALID_COMMAND = 102,
    RBRGEN3_HARDWARE_ERROR_PROTECTED_COMMAND = 103,
    RBRGEN3_HARDWARE_ERROR_FEATURE_NOT_YET_IMPLEMENTED = 104,
    RBRGEN3_HARDWARE_ERROR_COMMAND_PROHIBITED_WHILE_LOGGING = 105,
    RBRGEN3_HARDWARE_ERROR_EXPECTED_ARGUMENT_MISSING = 107,
    RBRGEN3_HARDWARE_ERROR_INVALID_ARGUMENT_TO_COMMAND = 108,
    RBRGEN3_HARDWARE_ERROR_FEATURE_NOT_AVAILABLE = 109,
    RBRGEN3_HARDWARE_ERROR_BUFFER_FULL = 110,
    RBRGEN3_HARDWARE_ERROR_COMMAND_FAILED = 111,
    RBRGEN3_HARDWARE_ERROR_EXPECTED_DATA_MISSING = 112,
    RBRGEN3_HARDWARE_ERROR_INVALID_DATA = 113,
    RBRGEN3_HARDWARE_ERROR_FEATURE_NOT_SUPPORTED_BY_HARDWARE = 114,
    RBRGEN3_HARDWARE_ERROR_UNKNOWN_ERROR3 = 300,
    RBRGEN3_HARDWARE_ERROR_MEMORY_ERASE_NOT_COMPLETED = 301,
    RBRGEN3_HARDWARE_ERROR_UNKNOWN_ERROR4 = 400,
    RBRGEN3_HARDWARE_ERROR_ESTIMATED_MEMORY_USAGE_EXCEEDS_CAPACITY = 401,
    RBRGEN3_HARDWARE_ERROR_MEMORY_NOT_EMPTY_ERASE_FIRST = 402,
    RBRGEN3_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_START_TIME = 403,
    RBRGEN3_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_CURRENT_TIME = 404,
    RBRGEN3_HARDWARE_ERROR_FAILED_TO_ENABLE_FOR_LOGGING = 405,
    RBRGEN3_HARDWARE_ERROR_NOT_LOGGING = 406,
    RBRGEN3_HARDWARE_ERROR_LOGGING_ALREADY_ACTIVE = 408,
    RBRGEN3_HARDWARE_ERROR_UNCLEARED_ERROR_USE_ERRORLOG = 409,
    RBRGEN3_HARDWARE_ERROR_NO_SAMPLING_CHANNELS_ACTIVE = 410,
    RBRGEN3_HARDWARE_ERROR_PERIOD_NOT_VALID_FOR_SELECTED_MODE = 411,
    RBRGEN3_HARDWARE_ERROR_BURST_PARAMETERS_INCONSISTENT = 412,
    RBRGEN3_HARDWARE_ERROR_PERIOD_TOO_SHORT_FOR_SERIAL_STREAMING = 413,
    RBRGEN3_HARDWARE_ERROR_THRESHOLDING_INTERVAL_NOT_VALID = 414,
    RBRGEN3_HARDWARE_ERROR_MORE_THAN_ONE_GATING_CONDITION_IS_ENABLED = 415,
    RBRGEN3_HARDWARE_ERROR_WRONG_REGIMES_SETTING = 416,
    RBRGEN3_HARDWARE_ERROR_NO_GATING_ALLOWED_WITH_REGIMES_MODE = 417,
    RBRGEN3_HARDWARE_ERROR_CAST_DETECTION_NEEDS_A_PRESSURE_DEPTH_CHANNEL = 418,
    RBRGEN3_HARDWARE_ERROR_CALIBRATION_COEFFICIENTS_ARE_MISSING = 419,
    RBRGEN3_HARDWARE_ERROR_REQUIRED_CHANNEL_IS_TURNED_OFF = 420,
    RBRGEN3_HARDWARE_ERROR_RAW_OUTPUT_FORMAT_NOT_ALLOWED = 421,
    RBRGEN3_HARDWARE_ERROR_AUX1_NOT_AVAILABLE_IN_CURRENT_SERIAL_MODE = 422,
    RBRGEN3_HARDWARE_ERROR_WRONG_DDSAMPLING_SETTINGS = 423,
    RBRGEN3_HARDWARE_ERROR_UNKNOWN_ERROR5 = 500,
    RBRGEN3_HARDWARE_ERROR_ITEM_IS_NOT_CONFIGURED = 501,
    RBRGEN3_HARDWARE_ERROR_CONFIGURATION_FAILED = 502,
    RBRGEN3_HARDWARE_ERROR_ALL_AVAILABLE_CHANNELS_ASSIGNED = 503,
    RBRGEN3_HARDWARE_ERROR_ADDRESS_ALREADY_IN_USE = 504,
    RBRGEN3_HARDWARE_ERROR_NO_CHANNELS_CONFIGURED = 505,
    RBRGEN3_HARDWARE_ERROR_CAN_NOT_CREATE_CALIBRATION_ENTRY = 506,
    RBRGEN3_HARDWARE_ERROR_CAN_NOT_DELETE_CALIBRATION_ENTRY = 507,
    RBRGEN3_HARDWARE_ERROR_UNKNOWN_ERROR6 = 600,
    RBRGEN3_HARDWARE_ERROR_NO_CALIBRATION_FOR_CHANNEL = 601,
} RBRGen3HardwareError;

/**
 * \brief Get a human-readable string name for a hardware error.
 *
 * \param [in] error the hardware error
 * \return a string name for the hardware error
 * \see RBRGen3Error_name() for a description of the format of names
 */
const char *RBRGen3HardwareError_name(RBRGen3HardwareError error);

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRGEN3HARDWAREERRORS_H */
