/**
 * \file RBRInstrumentGen4Memory.h
 *
 * \brief Instrument commands and structures pertaining to memory and data
 * retrieval.
 *
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRINSTRUMENTGEN4MEMORY_H
#define LIBRBR_RBRINSTRUMENTGEN4MEMORY_H

#include "RBRInstrumentGen4.h"
#include "RBRInstrumentGen4Configuration.h"
#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief The maximum number of channels which can be generated by a
 * post-processing job.
 */
#define RBRINSTRUMENTGEN4_POSTPROCESSING_CHANNEL_MAX 24

/** \brief The maximum number of datasetPool currently stored in the logger's memory.
 * The DATASET_MAX is defined in makefile CFLAGS.
*/
#define RBRINSTRUMENTGEN4_DATASET_COUNT_MAX 32

/**
 * \brief Instrument `storage` command parameters. Read-only.
 * \readonly
 *
 * \see RBRInstrumentGen4_getStorage()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13828279/storage
 */
typedef struct RBRInstrumentGen4Storage
{
    /** 
     * \brief The number of bytes being used to store data in the dataset.
     * \readonly
     */
    const int32_t used;
    /**
     * \brief The number of bytes available for data storage.
     * \readonly
     */
    const int32_t remaining;
    /**
     * \brief The maximum total size of the dataset in bytes.
     * \readonly
     */
    const int32_t size;
} RBRInstrumentGen4Storage;

/**
 * \brief Get information about the usage and characteristics of data memory.
 * \note Issues `storage` instrument command.
 *
 * \param [in] instrument the instrument connection
 * \param [out] storage data memory information
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when an invalid dataset is
 *                                                requested
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR if the dataset is unsupported
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13828279/storage
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getStorage(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Storage *storage);

/**
 * \brief Possible dataset states.
 *
 * \see RBRInstrumentGen4Dataset
 */
typedef enum RBRInstrumentGen4DatasetStatus
{
    /** The dataset is for a deployment currently in progress. */
    RBRINSTRUMENTGEN4_DATASET_STATUS_OPEN,
    /** For a historical dataset in memory which is no longer being updated because its deployment has stopped. */
    RBRINSTRUMENTGEN4_DATASET_STATUS_CLOSED,
    /** The number of specific dataset statuses. */
    RBRINSTRUMENTGEN4_DATASET_STATUS_COUNT,
    /** An unknown or unrecognized dataset status. */
    RBRINSTRUMENTGEN4_UNKNOWN_DATASET_STATUS
} RBRInstrumentGen4DatasetStatus;

/**
 * \brief Get a human-readable string name for a dataset status.
 *
 * \param [in] state the dataset status
 * \return a string name for the dataset status
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4DatasetStatus_name(RBRInstrumentGen4DatasetStatus status);


/**
 * \brief `dataset <dataset_label>` command parameters.
 * Reports read-only information about the specified dataset in storage.
 */
typedef struct RBRInstrumentGen4Dataset
{
    /** \brief the dataset label. */
    char label[RBRINSTRUMENTGEN4_LABEL_NAME_MAX+1];

    /** \brief "open" if the dataset is for a deployment currently in progress,
     * or "closed" for a historical dataset in memory which is no longer being updated
     * because its deployment has stopped.
     */
    const RBRInstrumentGen4DatasetStatus status;

    /** 
     * \brief The schedules executed during the deployment associated with this dataset. 
     * \note Note: the logger reports the dataset's schedules as they were when the specified dataset was started, not as they are presently defined, so the schedule objects used should not be edited/renamed/deleted after a deployment has finished.
     */
    RBRInstrumentGen4Config *config;

    /** \brief The memory usage in bytes. */
    int32_t byteCount;

    /** \brief The numerical format used for data storage in this dataset.
     * \see RBRInstrumentGen4DataType
     */
    const RBRInstrumentGen4DataType dataType;
} RBRInstrumentGen4Dataset;

typedef struct RBRInstrumentGen4DatasetInfo{
    /** \brief The memory usage for this schedule in bytes. */
    int32_t byteCount;

    /** \brief The memory usage for this schedule in samples. */
    int32_t sampleCount;

    /** \brief The memory usage for this schedule in events. */
    int32_t eventCount;
} RBRInstrumentGen4DatasetInfo;

/** \brief `dataset` command parameters. 
* \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
*/
typedef struct RBRInstrumentGen4DatasetPool {
    /** \brief The number of active datasetPool. Starts from 1. */
    int32_t count;

    /**
     * \brief The pointer array to all datasetPool.
     */
    RBRInstrumentGen4Dataset pool[RBRINSTRUMENTGEN4_DATASET_COUNT_MAX];
}RBRInstrumentGen4DatasetPool;

/** \brief Populate the pool of datasets with the labels of the datasets stored in the logger.
 * \param [in] instrument the instrument connection.
 * \param [inout] datasetPool the populated pool of datasets in storage.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
*/
RBRInstrumentGen4Error RBRInstrumentGen4_getDatasetPool(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4DatasetPool *datasetPool);

/** \brief Get information about the specified dataset in storage.
 * \param [in] instrument the instrument connection.
 * \param [in] configPool the list of available configs to associate the dataset with.
 * \param [inout] dataset the information about specified dataset in storage.
 * Note if one wants to get the memory use of a specific schedule or block, 
 * \see RBRInstrumentGen4_getDatasetByBlock 
 * \see RBRInstrumentGen4_getDatasetBySchedule
 * \see RBRInstrumentGen4_getDatasetByScheduleBlock
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
*/
RBRInstrumentGen4Error RBRInstrumentGen4_getDataset(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4ConfigPool *configPool,
    RBRInstrumentGen4Dataset *dataset);

/** \brief It determines the type of information retrieved for the specific schedule. 
 * There are three keywoards: data|events|meta.
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/dataset
*/
typedef enum RBRInstrumentGen4Block{
    /** Used to report memory usage for sample data. */
    RBRINSTRUMENTGEN4_BLOCK_DATA,
    /** Used to report memory usege for events. */
    RBRINSTRUMENTGEN4_BLOCK_EVENTS,
    /** Used to report this schedule's meory usage for metadata. */
    RBRINSTRUMENTGEN4_BLOCK_META,
    /** The number of specific type of blocks.*/
    RBRINSTRUMENTGEN4_BLOCK_COUNT,
    /** */
    RBRINSTRUMENTGEN4_BLOCK_ALL,
    /** The unknown or unrecognized block. */
    RBRINSTRUMENTGEN4_BLOCK_UNKNOWN
}RBRInstrumentGen4Block;

/** \brief Get a human-readable block name.
 * \param [in] block the block.
 * \return a string name for the block.
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4Block_name(RBRInstrumentGen4Block block);

/**
 * \brief Get information about the specified dataset in storage by block.
 * \param [in] instrument the instrument connection.
 * \param [in] block the dataset block.
 * \param [in] dataset the dataset in storage.
 * \param [out] datasetInfo the information about the specified dataset's block.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/dataset
*/
RBRInstrumentGen4Error RBRInstrumentGen4_getDatasetByBlock(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Block block,
    RBRInstrumentGen4Dataset *dataset,
    RBRInstrumentGen4DatasetInfo *datasetInfo);

/**
 * \brief Get information about the specified dataset in storage by block.
 * \param [in] instrument the instrument connection.
 * \param [in] schedule the schedule.
 * \param [in] dataset the dataset in storage.
 * \param [out] datasetInfo the information about the specified dataset's block.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/dataset
*/
RBRInstrumentGen4Error RBRInstrumentGen4_getDatasetBySchedule(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Schedule *schedule,
    RBRInstrumentGen4Dataset *dataset,
    RBRInstrumentGen4DatasetInfo *datasetInfo);

/**
 * \brief Get information about the specified dataset in storage by block.
 * \param [in] instrument the instrument connection.
 * \param [in] schedule the schedule.
 * \param [in] block the dataset block.
 * \param [in] dataset the dataset in storage.
 * \param [out] datasetInfo the dataset's block's memory consumption.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/dataset
*/
RBRInstrumentGen4Error RBRInstrumentGen4_getDatasetByScheduleBlock(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Schedule *schedule,
    RBRInstrumentGen4Block block,
    RBRInstrumentGen4Dataset *dataset,
    RBRInstrumentGen4DatasetInfo *datasetInfo);

/** \brief Delete specified dataset in storage.
 * \param [in] instrument the instrument connection.
 * \param [in] dataset the dataset to be deleted.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/datasetPool
*/

RBRInstrumentGen4Error RBRInstrumentGen4_deleteDataset(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Dataset *dataset);

/** \brief Delete all datasetPool in memory.
 * \param [in] instrument the instrument connection.
 * \param [inout] datasetPool the datasetPool.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/datasetPool
*/
RBRInstrumentGen4Error RBRInstrumentGen4_deleteDatasetAll(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4DatasetPool *datasetPool);

/** \brief The countKey for `download` command. It specifies the quantity of information that
 * the instrument should attempt to retrieve and report. 
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/download
*/
typedef enum RBRInstrumentGen4CountKey{
    /** Indicates that the information is measured in bytes. This option is
     * available for all three block types: data|events|meta.
    */
    RBRINSTRUMENTGEN4_COUNTKEY_BYTECOUNT,
    /** Can be used only with the data block type, and indicates that the 
     * information is measured in samples.
    */
    RBRINSTRUMENTGEN4_COUNTKEY_SAMPLECOUNT,
    /** Can be used only with events block type, and indicates that the information
     * is measured in events.
    */
    RBRINSTRUMENTGEN4_COUNTKEY_EVENTCOUNT,
    /** The number of specific type of countKey. */
    RBRINSTRUMENTGEN4_COUNTKEY_COUNT,
    /** Unknown or unrecognized countKey. */
    RBRINSTRUMENTGEN4_UNKNOWN_COUNTKEY
}RBRInstrumentGen4CountKey;

/** \brief Get a human-readable countKey name.
 * \param [in] countKey the countKey.
 * \return a string name for the countKey.
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4CountKey_name(RBRInstrumentGen4CountKey countKey);

/**
 * \brief Instrument `download` command parameters.
 *
 * \see RBRInstrumentGen4_download()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13830106/download
 */
typedef struct RBRInstrumentGen4Download{
    /** \brief Identifies the complete dataset corresponding to the deployment of interest. */
    RBRInstrumentGen4Dataset *dataset;

    /** \brief identifies the sampling schedule used to acquire the data.  For a list of available schedules, use dataset dataset_label scheduleList.*/
    RBRInstrumentGen4Schedule *schedule;

    /** \brief It is one of the three keywords data, events, or meta, and determines the type of data retrieved for the specified schedule.*/
    RBRInstrumentGen4Block block;

    /** \brief The quantity of information that the instrument should attempt to retrieve and report.
     * It also determines the 'units' in which the information will be measured:
     * 
     * The bytecount count_key indicates that the information is measured in bytes; 
     * this option is available for all three block types, data, events and meta.
     * 
     * The sampleCount count_key can be used only with the data block type, and 
     * indicates that the information is measured in samples.
     * 
     * The eventCount count_key can be used only with the events block type, 
     * and indicates that the information is measured in events.
     * Any transfer from a given storage object that uses multiple download 
     * commands must all use the same measurement units.
    */
    RBRInstrumentGen4CountKey countKey;

    /** \brief The response for count_key. */
    int32_t countValue;

    /** \brief An offset from the beginning of the storage object where 
     * reading should begin.  It is measured in the same units used for the 
     * count_key; one of bytes, samples, or events.  The first item always 
     * has start = 1.*/
    RBRInstrumentGen4CountKey startKey;

    /** \brief The response for start_key. */
    int32_t startOffset;

    /** \brief The data read from the instrument. */
    void *data;
}RBRInstrumentGen4Download;

/** \brief Reads all or part of specified storage object. For the initial use
 * of the `download` command, all parameters are required. 
 * 
 * In all cases, if the requested amount of data would overrun the boundary of 
 * the target object, a valid transfer still occurs, but the amount of data 
 * actually returned will be less than the request.  This is reflected in the 
 * instrument's response to the command.
 * 
 * \param [in] instrument the instrument connection.
 * \param [inout] download all or part of a specified storage object.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/datasetPool
*/
RBRInstrumentGen4Error RBRInstrumentGen4_download(RBRInstrumentGen4 *instrument,
                                          RBRInstrumentGen4Download *download);

/*****************************************************************************************************************/
/**
 * \brief Functions available to aggregate channel values within bins.
 *
 * \see RBRInstrumentGen4PostprocessingChannel
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13830106/download
 */
typedef enum RBRInstrumentGen4PostprocessingAggregate
{
    /** average value in the bin */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_MEAN,
    /** standard deviation of the bin */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_STD,
    /** number of samples in the bin */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT,
    /** The number of specific post-processing aggregate functions. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_COUNT,
    /** An unknown or unrecognized post-processing aggregate function. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_AGGREGATE
} RBRInstrumentGen4PostprocessingAggregate;

/**
 * \brief Get a human-readable string name for an aggregate function.
 *
 * For consistency with the instrument command language, returns “count”, not
 * “sample count”, for #RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT.
 * The value name only includes `_SAMPLE` to disambiguate between the aggregate
 * function and the value which is the count of valid values,
 * #RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_COUNT.
 *
 * \param [in] function the aggregate function
 * \return a string name for the aggregate function
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingAggregate_name(
    RBRInstrumentGen4PostprocessingAggregate function);

/**
 * Post-processing channel configurations.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef struct RBRInstrumentGen4PostprocessingChannelList
{
    /** \brief The number of channels generated by post-processing. */
    int32_t count;
    /** \brief The definitions of post-processing channels. */
    struct
    {
        /** \brief The function used to aggregate values within bins. */
        RBRInstrumentGen4PostprocessingAggregate function;
        /** \brief The label of the channel to aggregate. */
        char label[RBRINSTRUMENTGEN4_CHANNEL_LABEL_MAX + 1];
    } channels[RBRINSTRUMENTGEN4_POSTPROCESSING_CHANNEL_MAX];
} RBRInstrumentGen4PostprocessingChannelList;

/**
 * \brief Post-processing job statuses.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen4PostprocessingStatus
{
    /** Post-processing is idle. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_IDLE,
    /** Post-processing is in progress. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_PROCESSING,
    /** Post-processing has completed. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_COMPLETED,
    /** Post-processing has been aborted. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_ABORTED,
    /** The number of specific post-processing statuses. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_COUNT,
    /** An unknown or unrecognized post-processing status. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_STATUS
} RBRInstrumentGen4PostprocessingStatus;

/**
 * \brief Get a human-readable string name for a post-processing status.
 *
 * \param [in] status the post-processing status
 * \return a string name for the post-processing status
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingStatus_name(
    RBRInstrumentGen4PostprocessingStatus status);

/**
 * \brief Post-processing control commands.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen4PostprocessingCommand
{
    /** Start the post-processing job. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_START,
    /** Reset the post-processing job. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_RESET,
    /** Abort any current post-processing job. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_ABORT,
    /** The number of specific post-processing commands. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_COUNT,
    /** An unknown or unrecognized post-processing command. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_COMMAND
} RBRInstrumentGen4PostprocessingCommand;

/**
 * \brief Get a human-readable string name for a post-processing command.
 *
 * \param [in] command the post-processing command
 * \return a string name for the post-processing command
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingCommand_name(
    RBRInstrumentGen4PostprocessingCommand command);

/**
 * \brief Post-processing bin filters.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen4PostprocessingBinFilter
{
    /** No filter. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_NONE,
    /**
     * \brief Only ascending values.
     *
     * Equivalent to ascending regimes binning. Only valid when binning by
     * depth.
     */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_ASCENTONLY,
    /**
     * \brief Only descending values.
     *
     * Equivalent to descending regimes binning. Only valid when binning by
     * depth.
     */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_DESCENTONLY,
    /** The number of specific post-processing bin filters. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_COUNT,
    /** An unknown or unrecognized post-processing bin filter. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_BINFILTER
} RBRInstrumentGen4PostprocessingBinFilter;

/**
 * \brief Get a human-readable string name for a post-processing bin filter.
 *
 * \param [in] filter the post-processing bin filter
 * \return a string name for the post-processing bin filter
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingBinFilter_name(
    RBRInstrumentGen4PostprocessingBinFilter filter);

/**
 * \brief The instrument post-processing configuration.
 *
 * \see RBRInstrumentGen4_getPostprocessing()
 * \see RBRInstrumentGen4_setPostprocessing()
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef struct RBRInstrumentGen4Postprocessing
{
    /**
     * \brief The current state of the instrument's post-processing function.
     *
     * \readonly
     */
    RBRInstrumentGen4PostprocessingStatus status;
    /**
     * \brief Post-processing statistics channel configurations.
     *
     * Functions which receive an RBRInstrumentGen4Postprocessing instance will
     * expect the first RBRInstrumentGen4PostprocessingchannelList.count entries to
     * be populated, and functions which return a RBRInstrumentGen4Postprocessing
     * instance will similarly indicate how many entries are populated.
     */
    RBRInstrumentGen4PostprocessingChannelList channels;
    /**
     * \brief The reference channel for binning.
     *
     * If the reference is set to the keyword `tstamp`, the generated data will
     * be binned by time. Otherwise, if the reference is set to the channel
     * label of a pressure or sea pressure channel, the generated data is
     * binned by depth.
     */
    char binReference[RBRINSTRUMENTGEN4_CHANNEL_LABEL_MAX + 1];
    /** \brief How data should be filtered before binning. */
    RBRInstrumentGen4PostprocessingBinFilter binFilter;
    /**
     * \brief The size of each bin.
     *
     * When binning by time: specified in milliseconds, with a precision of
     * milliseconds.
     *
     * When binning by depth: specified in decibars, with a minimum precision
     * of 0.1 dbar.
     *
     * The bin size can always be set to 0, in which case, no binning is
     * performed.
     *
     * The bin size may never be negative.
     */
    float binSize;
    /**
     * \brief The minimum timestamp value.
     *
     * All samples with an earlier timestamp are excluded from post-processing
     * input. If time binning is used, this serves as the binning origin point.
     */
    RBRInstrumentGen4DateTime tstampMin;
    /**
     * \brief The maximum timestamp value.
     *
     * All samples with a later timestamp are excluded from post-processing
     * input.
     */
    RBRInstrumentGen4DateTime tstampMax;
    /**
     * \brief The minimum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a lesser depth are excluded from
     * post-processing input; and unless the bin filter is set to
     * #RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_ASCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMin;
    /**
     * \brief The maximum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a greater depth are excluded
     * from post-processing input; and if the bin filter is set to
     * #RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_DESCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMax;
    /**
     * \brief (dynamic correction) Alpha parameter from Lueck and Picklo equation
     *
     * Coefficient is unitless (default 0.08)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcAlpha;
    /**
     * \brief (dynamic correction) Tau parameter from Lueck and Picklo equation (1/beta)
     *
     * Coefficient is unitless (default 8.000)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTau;
    /**
     * \brief (dynamic correction) Parameter for the time lag correction 
     *          between marine temperature and conductivity cell temperature
     *
     * Coefficient is in second (default 0.35)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTdelay;
    /**
     * \brief (dynamic correction) Parameter for the long term thermal coefficient
     *                  for the conductivity cell
     *
     * Coefficient is in 1/celcius (default 2.4e-4)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcCtCoeff;
} RBRInstrumentGen4Postprocessing;

/**
 * \brief Get the instrument post-processing settings.
 *
 * \param [in] instrument the instrument connection
 * \param [out] postprocessing the post-processing parameters
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getPostprocessing(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Postprocessing *postprocessing);

/**
 * \brief Set the instrument post-processing settings.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - a post-processing job is already running
 * - you set an out-of-bounds parameter the library fails to detect
 *
 * \param [in] instrument the instrument connection
 * \param [in] postprocessing the post-processing parameters
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the settings cannot be changed
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setPostprocessing(
    RBRInstrumentGen4 *instrument,
    const RBRInstrumentGen4Postprocessing *postprocessing);

/**
 * \brief Exercises control over the post-processing state.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - post-processing settings are invalid
 * - the wrong memory format is in use
 * - the requested reference channel is unavailable
 *
 * \param [in] instrument the instrument connection
 * \param [in] command the post-processing command
 * \param [out] status the post-processing status after executing the command
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the settings cannot be changed
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setPostprocessingCommand(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4PostprocessingCommand command,
    RBRInstrumentGen4PostprocessingStatus *status);

/**
 * \brief Calculate the 16-bit CRC using the CCITT polynomial f(x)=x^16+x^12+x^5+1
 * feeding bytes into the generator LSB first and using 0xFFFF as a seed value,
 * is then transmitted.
 *
 * \param [in] data the data string used to calculate the CRC
 * \param [in] size the number of characters in the string used to calculate the CRC
 * \return calculated CRC
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
uint16_t calculateCrc(
    const void *data,
    int32_t size);   

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRINSTRUMENTMEMORY_H */
