/**
 * \file RBRInstrumentGen4HardwareErrors.h
 *
 * \brief Instrument hardware errors.
 *
 * \see https://docs.rbr-global.com/L3commandreference/error-messages
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRINSTRUMENTGEN4HARDWAREERRORS_H
#define LIBRBR_RBRINSTRUMENTGEN4HARDWAREERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief Errors which can be returned by the instrument.
 */
typedef enum RBRInstrumentGen4HardwareError
{
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_NONE                                          =   0,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_COMMAND_PARSER_BUSY                           = 101,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_INVALID_COMMAND                               = 102,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_PROTECTED_COMMAND                             = 103,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_FEATURE_NOT_YET_IMPLEMENTED                   = 104,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_COMMAND_PROHIBITED_WHILE_LOGGING              = 105,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_EXPECTED_ARGUMENT_MISSING                     = 107,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_INVALID_ARGUMENT_TO_COMMAND                   = 108,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_FEATURE_NOT_AVAILABLE                         = 109,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_BUFFER_FULL                                   = 110,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_COMMAND_FAILED                                = 111,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_EXPECTED_DATA_MISSING                         = 112,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_INVALID_DATA                                  = 113,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_FEATURE_NOT_SUPPORTED_BY_HARDWARE             = 114,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_SYNTAX_ERROR                                  = 115,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNKNOWN_QUALIFIER                             = 117,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_INVALID_QUALIFIER                             = 118,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_MISSING_QUALIFIER                             = 119,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_LABEL_ALREADY_IN_USE                          = 120,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_PARAMETER_IS_READ_ONLY                        = 125,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_MISPLACED_ARGUMENT                            = 128,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_ILLEGAL_CHARACTER_IN_LABEL                    = 131,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_QUALIFIER_USED_BY_ANOTHER_OBJECT              = 170,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNKNOWN_ERROR3                                = 300,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_MEMORY_ERASE_NOT_COMPLETED                    = 301,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_DOWNLOAD_TRACKING_FAILED                      = 302,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_STORAGE_ACCESS_MUST_BE_SET_TO_INSTRUMENT      = 303,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_DATASET_NOT_FOUND                             = 304,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_STORAGE_ACCESS_ALREADY_AT_SELECTED_LOCATION   = 305,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNKNOWN_ERROR4                                = 400,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_ESTIMATED_MEMORY_USAGE_EXCEEDS_CAPACITY       = 401,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_MEMORY_NOT_EMPTY_ERASE_FIRST                  = 402,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_START_TIME             = 403,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_CURRENT_TIME           = 404,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_FAILED_TO_ENABLE_FOR_LOGGING                  = 405,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_NOT_LOGGING                                   = 406,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_CANNOT_RESUME_UNLESS_PAUSED                   = 407,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_LOGGING_ALREADY_ACTIVE                        = 408,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNCLEARED_ERROR_USE_ERRORLOG                  = 409,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_NO_SAMPLING_CHANNELS_ACTIVE                   = 410,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_PERIOD_NOT_VALID_FOR_SELECTED_MODE            = 411,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_BURST_PARAMETERS_INCONSISTENT                 = 412,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_PERIOD_TOO_SHORT_FOR_SERIAL_STREAMING         = 413,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_THRESHOLDING_INTERVAL_NOT_VALID               = 414,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_MORE_THAN_ONE_GATING_CONDITION_IS_ENABLED     = 415,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_WRONG_REGIMES_SETTING                         = 416,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_NO_GATING_ALLOWED_WITH_REGIMES_MODE           = 417,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_CAST_DETECTION_NEEDS_A_PRESSURE_DEPTH_CHANNEL = 418,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_CALIBRATION_COEFFICIENTS_ARE_MISSING          = 419,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_REQUIRED_CHANNEL_IS_TURNED_OFF                = 420,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_RAW_OUTPUT_FORMAT_NOT_ALLOWED                 = 421,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_AUX1_NOT_AVAILABLE_IN_CURRENT_SERIAL_MODE     = 422,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_WRONG_DDSAMPLING_SETTINGS                     = 423,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNABLE_TO_ESTIMATE_MEMORY_USAGE               = 429,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_EMPTY_SCHEDULE_LIST_IN_CONFIGURATION          = 430,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_DATASET_LIMIT_REACHED                         = 431,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_INSTRUMENT_STATE_IS_ALREADY_DISABLED          = 435,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_ALREADY_ENABLED_WITH_DIFFERENT_SETTINGS       = 436,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNKNOWN_ERROR5                                = 500,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_ITEM_IS_NOT_CONFIGURED                        = 501,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_CONFIGURATION_FAILED                          = 502,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_ALL_AVAILABLE_CHANNELS_ASSIGNED               = 503,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_ADDRESS_ALREADY_IN_USE                        = 504,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_NO_CHANNELS_CONFIGURED                        = 505,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_CAN_NOT_CREATE_CALIBRATION_ENTRY              = 506,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_CAN_NOT_DELETE_CALIBRATION_ENTRY              = 507,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_UNKNOWN_ERROR6                                = 600,
    RBRINSTRUMENTGEN4_HARDWARE_ERROR_NO_CALIBRATION_FOR_CHANNEL                    = 601
} RBRInstrumentGen4HardwareError;

/**
 * \brief Get a human-readable string name for a hardware error.
 *
 * \param [in] error the hardware error
 * \return a string name for the hardware error
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4HardwareError_name(RBRInstrumentGen4HardwareError error);

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRINSTRUMENTINTERNAL_H */
