/**
 * \file RBRInstrumentHardwareErrors.h
 *
 * \brief Instrument hardware errors.
 *
 * \see https://docs.rbr-global.com/L3commandreference/error-messages
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRINSTRUMENTHARDWAREERRORS_H
#define LIBRBR_RBRINSTRUMENTHARDWAREERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief Errors which can be returned by the instrument.
 */
typedef enum RBRInstrumentHardwareError
{
    RBRINSTRUMENT_HARDWARE_ERROR_NONE                                          =   0,
    RBRINSTRUMENT_HARDWARE_ERROR_COMMAND_PARSER_BUSY                           = 101,
    RBRINSTRUMENT_HARDWARE_ERROR_INVALID_COMMAND                               = 102,
    RBRINSTRUMENT_HARDWARE_ERROR_PROTECTED_COMMAND                             = 103,
    RBRINSTRUMENT_HARDWARE_ERROR_FEATURE_NOT_YET_IMPLEMENTED                   = 104,
    RBRINSTRUMENT_HARDWARE_ERROR_COMMAND_PROHIBITED_WHILE_LOGGING              = 105,
    RBRINSTRUMENT_HARDWARE_ERROR_EXPECTED_ARGUMENT_MISSING                     = 107,
    RBRINSTRUMENT_HARDWARE_ERROR_INVALID_ARGUMENT_TO_COMMAND                   = 108,
    RBRINSTRUMENT_HARDWARE_ERROR_FEATURE_NOT_AVAILABLE                         = 109,
    RBRINSTRUMENT_HARDWARE_ERROR_BUFFER_FULL                                   = 110,
    RBRINSTRUMENT_HARDWARE_ERROR_COMMAND_FAILED                                = 111,
    RBRINSTRUMENT_HARDWARE_ERROR_EXPECTED_DATA_MISSING                         = 112,
    RBRINSTRUMENT_HARDWARE_ERROR_INVALID_DATA                                  = 113,
    RBRINSTRUMENT_HARDWARE_ERROR_FEATURE_NOT_SUPPORTED_BY_HARDWARE             = 114,
    RBRINSTRUMENT_HARDWARE_ERROR_UNKNOWN_ERROR3                                = 300,
    RBRINSTRUMENT_HARDWARE_ERROR_MEMORY_ERASE_NOT_COMPLETED                    = 301,
    RBRINSTRUMENT_HARDWARE_ERROR_UNKNOWN_ERROR4                                = 400,
    RBRINSTRUMENT_HARDWARE_ERROR_ESTIMATED_MEMORY_USAGE_EXCEEDS_CAPACITY       = 401,
    RBRINSTRUMENT_HARDWARE_ERROR_MEMORY_NOT_EMPTY_ERASE_FIRST                  = 402,
    RBRINSTRUMENT_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_START_TIME             = 403,
    RBRINSTRUMENT_HARDWARE_ERROR_END_TIME_MUST_BE_AFTER_CURRENT_TIME           = 404,
    RBRINSTRUMENT_HARDWARE_ERROR_FAILED_TO_ENABLE_FOR_LOGGING                  = 405,
    RBRINSTRUMENT_HARDWARE_ERROR_NOT_LOGGING                                   = 406,
    RBRINSTRUMENT_HARDWARE_ERROR_LOGGING_ALREADY_ACTIVE                        = 408,
    RBRINSTRUMENT_HARDWARE_ERROR_UNCLEARED_ERROR_USE_ERRORLOG                  = 409,
    RBRINSTRUMENT_HARDWARE_ERROR_NO_SAMPLING_CHANNELS_ACTIVE                   = 410,
    RBRINSTRUMENT_HARDWARE_ERROR_PERIOD_NOT_VALID_FOR_SELECTED_MODE            = 411,
    RBRINSTRUMENT_HARDWARE_ERROR_BURST_PARAMETERS_INCONSISTENT                 = 412,
    RBRINSTRUMENT_HARDWARE_ERROR_PERIOD_TOO_SHORT_FOR_SERIAL_STREAMING         = 413,
    RBRINSTRUMENT_HARDWARE_ERROR_THRESHOLDING_INTERVAL_NOT_VALID               = 414,
    RBRINSTRUMENT_HARDWARE_ERROR_MORE_THAN_ONE_GATING_CONDITION_IS_ENABLED     = 415,
    RBRINSTRUMENT_HARDWARE_ERROR_WRONG_REGIMES_SETTING                         = 416,
    RBRINSTRUMENT_HARDWARE_ERROR_NO_GATING_ALLOWED_WITH_REGIMES_MODE           = 417,
    RBRINSTRUMENT_HARDWARE_ERROR_CAST_DETECTION_NEEDS_A_PRESSURE_DEPTH_CHANNEL = 418,
    RBRINSTRUMENT_HARDWARE_ERROR_CALIBRATION_COEFFICIENTS_ARE_MISSING          = 419,
    RBRINSTRUMENT_HARDWARE_ERROR_REQUIRED_CHANNEL_IS_TURNED_OFF                = 420,
    RBRINSTRUMENT_HARDWARE_ERROR_RAW_OUTPUT_FORMAT_NOT_ALLOWED                 = 421,
    RBRINSTRUMENT_HARDWARE_ERROR_AUX1_NOT_AVAILABLE_IN_CURRENT_SERIAL_MODE     = 422,
    RBRINSTRUMENT_HARDWARE_ERROR_WRONG_DDSAMPLING_SETTINGS                     = 423,
    RBRINSTRUMENT_HARDWARE_ERROR_UNKNOWN_ERROR5                                = 500,
    RBRINSTRUMENT_HARDWARE_ERROR_ITEM_IS_NOT_CONFIGURED                        = 501,
    RBRINSTRUMENT_HARDWARE_ERROR_CONFIGURATION_FAILED                          = 502,
    RBRINSTRUMENT_HARDWARE_ERROR_ALL_AVAILABLE_CHANNELS_ASSIGNED               = 503,
    RBRINSTRUMENT_HARDWARE_ERROR_ADDRESS_ALREADY_IN_USE                        = 504,
    RBRINSTRUMENT_HARDWARE_ERROR_NO_CHANNELS_CONFIGURED                        = 505,
    RBRINSTRUMENT_HARDWARE_ERROR_CAN_NOT_CREATE_CALIBRATION_ENTRY              = 506,
    RBRINSTRUMENT_HARDWARE_ERROR_CAN_NOT_DELETE_CALIBRATION_ENTRY              = 507,
    RBRINSTRUMENT_HARDWARE_ERROR_UNKNOWN_ERROR6                                = 600,
    RBRINSTRUMENT_HARDWARE_ERROR_NO_CALIBRATION_FOR_CHANNEL                    = 601
} RBRInstrumentHardwareError;

/**
 * \brief Get a human-readable string name for a hardware error.
 *
 * \param [in] error the hardware error
 * \return a string name for the hardware error
 * \see RBRInstrumentError_name() for a description of the format of names
 */
const char *RBRInstrumentHardwareError_name(RBRInstrumentHardwareError error);

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRINSTRUMENTINTERNAL_H */
