/**
 * \file RBRInstrumentGen4Security.h
 *
 * \brief Instrument commands and structures pertaining to command security and
 * interaction.
 *
 * \see https://docs.rbr-global.com/L3commandreference/commands/security-and-interaction
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRINSTRUMENTGEN4SECURITY_H
#define LIBRBR_RBRINSTRUMENTGEN4SECURITY_H

#ifdef __cplusplus
extern "C" {
#endif

#include "RBRInstrumentGen4.h"

/**
 * \brief Permits a protected command to be executed.
 *
 * Permits a protected command to be executed immediately after this one;
 * receipt of anything else removes the permission again. Any other constraints
 * on executing a particular command will still apply. It is not an error to
 * `permit` a command which does not need it, merely unnecessary.
 *
 * \param [in] instrument the instrument connection
 * \param [in] command the command to permit
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the command has been permitted
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR if the command can't be permitted
 * \see https://docs.rbr-global.com/L3commandreference/commands/security-and-interaction/permit
 */
RBRInstrumentGen4Error RBRInstrumentGen4_permit(RBRInstrumentGen4 *instrument,
                                        const char *command);

/**
 * \brief Get the state of the “Ready:” prompt.
 *
 * The prompt is normally sent by the logger in response to almost any command
 * after any other output generated by the command is complete.
 *
 * \param [in] instrument the instrument connection
 * \param [out] prompt whether the prompt is enabled
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the setting is successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/security-and-interaction/prompt
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getPrompt(RBRInstrumentGen4 *instrument,
                                           bool *prompt);

/**
 * \brief Set the state of the “Ready:” prompt.
 *
 * \param [in] instrument the instrument connection
 * \param [in] prompt whether the prompt should be enabled
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the setting is successfully written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/security-and-interaction/prompt
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setPrompt(RBRInstrumentGen4 *instrument,
                                           const bool prompt);

/**
 * \brief Get the state of the logger's confirmation responses.
 *
 * The confirmation responses are normally sent after a parameter has been
 * modified if the state is on.
 *
 * \param [in] instrument the instrument connection
 * \param [out] confirmation whether confirmation is enabled
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the setting is successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/security-and-interaction/confirmation
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getConfirmation(RBRInstrumentGen4 *instrument,
                                                 bool *confirmation);

/**
 * \brief Set the state of the logger's confirmation responses.
 *
 * This function permits confirmation to be set on or off. However, the rest of
 * the library expects confirmations to be on, and most setters will poll the
 * instrument until timeout with it off.
 *
 * \param [in] instrument the instrument connection
 * \param [in] confirmation whether confirmation should be enabled
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the setting is successfully written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/security-and-interaction/confirmation
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setConfirmation(RBRInstrumentGen4 *instrument,
                                                 const bool confirmation);

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRINSTRUMENTGEN4SECURITY_H */
