/**
 * \file RBRInstrumentGen3Memory.h
 *
 * \brief Instrument commands and structures pertaining to memory and data
 * retrieval.
 *
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRINSTRUMENTGEN3MEMORY_H
#define LIBRBR_RBRINSTRUMENTGEN3MEMORY_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief The maximum number of channels which can be generated by a
 * post-processing job.
 */
#define RBRINSTRUMENTGEN3_POSTPROCESSING_CHANNEL_MAX 24

/**
 * \brief Possible instrument datasets.
 *
 * As an internal implementation detail, the instrument reuses file identifiers
 * (for standard and EasyParse data), and the identifiers are non-continuous
 * (there is no dataset 3). To keep confusion to a minimum, we use those same
 * identifiers here.
 */
typedef enum RBRInstrumentGen3Dataset
{
    /** EasyParse events */
    RBRINSTRUMENTGEN3_DATASET_EASYPARSE_EVENTS = 0,
    /** Standard data */
    RBRINSTRUMENTGEN3_DATASET_STANDARD = 1,
    /** EasyParse sample data */
    RBRINSTRUMENTGEN3_DATASET_EASYPARSE_SAMPLE_DATA = 1,
    /** EasyParse deployment header */
    RBRINSTRUMENTGEN3_DATASET_EASYPARSE_DEPLOYMENT_HEADER = 2,
    /** Reserved for use by the instrument. Cannot be downloaded. */
    RBRINSTRUMENTGEN3_DATASET_UNKNOWN_DATASET1 = 3,
    /** Post-processing sample data */
    RBRINSTRUMENTGEN3_DATASET_POSTPROCESSING_SAMPLE_DATA = 4,
    /** The number of specific datasets. */
    RBRINSTRUMENTGEN3_DATASET_COUNT,
    /** An unknown or unrecognized dataset. */
    RBRINSTRUMENTGEN3_UNKNOWN_DATASET
} RBRInstrumentGen3Dataset;

/**
 * \brief Get a human-readable string name for a dataset.
 *
 * Contrary to convention for values returned by other enum `_name` functions,
 * instances of “EasyParse” found in the names returned by this function are
 * capitalized: “EasyParse sample data” instead of “easyparse sample data”.
 * And, because the standard and EasyParse sample data datasets share an
 * identifier, “standard or EasyParse data” is returned for that value.
 *
 * \param [in] dataset the dataset
 * \return a string name for the dataset
 * \see RBRInstrumentGen3Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen3Dataset_name(RBRInstrumentGen3Dataset dataset);

/**
 * \brief Instrument `meminfo` command parameters.
 *
 * \see RBRInstrumentGen3_getMemoryInfo()
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/meminfo
 */
typedef struct RBRInstrumentGen3MemoryInfo
{
    /** \brief The index of the dataset being queried. */
    RBRInstrumentGen3Dataset dataset;
    /** \brief The number of bytes being used to store data in the dataset. */
    int32_t used;
    /** \brief The number of bytes available for data storage. */
    int32_t remaining;
    /** \brief The maximum total size of the dataset in bytes. */
    int32_t size;
} RBRInstrumentGen3MemoryInfo;

/**
 * \brief Get information about the usage and characteristics of data memory.
 *
 * RBRInstrumentGen3MemoryInfo.dataset must be set to the index of the dataset for
 * which information is to be retrieved.
 *
 * ~~~{.c}
 * RBRInstrumentGen3MemoryInfo memoryInfo;
 * memoryInfo.dataset = RBRINSTRUMENTGEN3_DATASET_STANDARD;
 * RBRInstrumentGen3_getMemoryInfo(instrument, &memoryInfo);
 * ~~~
 *
 * \param [in] instrument the instrument connection
 * \param [in,out] memoryInfo data memory information
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_INVALID_PARAMETER_VALUE when an invalid dataset is
 *                                                requested
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR if the dataset is unsupported
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/meminfo
 */
RBRInstrumentGen3Error RBRInstrumentGen3_getMemoryInfo(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3MemoryInfo *memoryInfo);

/**
 * \brief Instrument `readdata` command parameters.
 *
 * \see RBRInstrumentGen3_readData()
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/readdata
 */
typedef struct RBRInstrumentGen3Data
{
    /** \brief The index of the dataset being queried. */
    RBRInstrumentGen3Dataset dataset;
    /** \brief The amount of data read. */
    int32_t size;
    /** \brief The offset in memory of the data. */
    int32_t offset;
    /** \brief The data read from the instrument. */
    void *data;
} RBRInstrumentGen3Data;

/**
 * \brief Request a chunk of binary data from instrument data memory.
 *
 * When calling RBRInstrumentGen3_readData(), \a data must be populated:
 *
 * - RBRInstrumentGen3Data.dataset must be the index of the dataset to read from
 * - RBRInstrumentGen3Data.size must be the maximum amount of data to read
 * - RBRInstrumentGen3Data.offset must be the offset in memory from which to read
 * - RBRInstrumentGen3Data.data must be a pointer to a location to which the data
 *   can be written
 *
 * Upon return, \a data will have been modified so that the dataset, size, and
 * offset reflect the the instrument response. Be sure to check the reported
 * size as it may differ from the requested size, especially when the
 * instrument is busy or if you're reading the last chunk of the dataset.
 *
 * For example:
 *
 * ~~~{.c}
 * uint8_t buf[1400];
 * RBRInstrumentGen3Data data = {
 *     .dataset = RBRINSTRUMENTGEN3_DATASET_STANDARD,
 *     .size    = 1400,
 *     .offset  = 2800,
 *     .data    = buf
 * };
 * RBRInstrumentGen3_readData(instrument, &data);
 * fwrite(buf, data.size, 1, datasetFile);
 * ~~~
 *
 * A communication error will be reported if the offset in response doesn't match request.
 * A checksum error will be reported if the CRC check of the read data fails.
 * However, \a data will still faithfully reflect the response parameters and
 * data. Be sure to check the return value lest you accidentally consume
 * invalid/corrupt data!
 *
 * \param [in] instrument the instrument connection
 * \param [in,out] data the instrument data
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_CHECKSUM_ERROR in the event of a CRC failure
 * \return #RBRINSTRUMENTGEN3_INVALID_PARAMETER_VALUE when an invalid dataset is
 *                                                requested
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR if the dataset is unsupported
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/readdata
 */
RBRInstrumentGen3Error RBRInstrumentGen3_readData(RBRInstrumentGen3 *instrument,
                                          RBRInstrumentGen3Data *data);

/**
 * \brief Clear the data storage area of the flash memory.
 *
 * Currently, all datasets are erased, regardless of the data storage format in
 * use.
 *
 * \param [in] instrument the instrument connection
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR if the memory failed to erase
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/memclear
 */
RBRInstrumentGen3Error RBRInstrumentGen3_memoryClear(RBRInstrumentGen3 *instrument);

/**
 * \brief Instrument memory formats.
 *
 * \see RBRInstrumentGen3_getAvailableMemoryFormats()
 * \see RBRInstrumentGen3_getCurrentMemoryFormat()
 * \see RBRInstrumentGen3_getNewMemoryFormat()
 * \see RBRInstrumentGen3_setNewMemoryFormat()
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/memformat
 */
typedef enum RBRInstrumentGen3MemoryFormat
{
    /** No format. */
    RBRINSTRUMENTGEN3_MEMFORMAT_NONE     =      0,
    /** “Standard” format, `rawbin00`. */
    RBRINSTRUMENTGEN3_MEMFORMAT_RAWBIN00 = 1 << 0,
    /** “EasyParse” format, `calbin00`. */
    RBRINSTRUMENTGEN3_MEMFORMAT_CALBIN00 = 1 << 1,
    /** Corresponds to the largest memory format enum value. */
    RBRINSTRUMENTGEN3_MEMFORMAT_MAX      = RBRINSTRUMENTGEN3_MEMFORMAT_CALBIN00
} RBRInstrumentGen3MemoryFormat;

/**
 * \brief Get a human-readable string name for a memory format.
 *
 * \param [in] format the memory format
 * \return a string name for the memory format
 * \see RBRInstrumentGen3Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen3MemoryFormat_name(RBRInstrumentGen3MemoryFormat format);

/**
 * \brief Report a list of available memory formats.
 *
 * \a memoryFormats will be treated as a bit field representation of available
 * memory formats as defined by RBRInstrumentGen3MemoryFormat. For details, consult
 * [Working with Bit Fields](bitfields.md).
 *
 * \param [in] instrument the instrument connection
 * \param [out] memoryFormats available memory formats
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/memformat
 */
RBRInstrumentGen3Error RBRInstrumentGen3_getAvailableMemoryFormats(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3MemoryFormat *memoryFormats);

/**
 * \brief Get the current memory format.
 *
 * Retrieves the format of the data presently stored in memory, either for a
 * deployment in progress or for one which has finished. If the memory is
 * completely empty because it has been cleared, the response will be
 * #RBRINSTRUMENTGEN3_MEMFORMAT_NONE.
 *
 * \param [in] instrument the instrument connection
 * \param [out] memoryFormat the current memory format
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/memformat
 */
RBRInstrumentGen3Error RBRInstrumentGen3_getCurrentMemoryFormat(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3MemoryFormat *memoryFormat);

/**
 * \brief Get the memory format to be used for the next deployment.
 *
 * \param [in] instrument the instrument connection
 * \param [out] memoryFormat the new memory format
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/memformat
 */
RBRInstrumentGen3Error RBRInstrumentGen3_getNewMemoryFormat(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3MemoryFormat *memoryFormat);

/**
 * \brief Set the memory format to be used for the next deployment.
 *
 * Hardware errors may occur if:
 *
 * - the instrument is logging
 * - you select an unavailable memory format
 *
 * \param [in] instrument the instrument connection
 * \param [in] memoryFormat the new memory format
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_INVALID_PARAMETER_VALUE when an invalid format is
 *                                                requested
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR when the instrument is logging or if
 *                                       an unavailable memory format is
 *                                       selected
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/memformat
 */
RBRInstrumentGen3Error RBRInstrumentGen3_setNewMemoryFormat(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3MemoryFormat memoryFormat);

/**
 * \brief Functions available to aggregate channel values within bins.
 *
 * \see RBRInstrumentGen3PostprocessingChannel
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen3PostprocessingAggregate
{
    /** average value in the bin */
    RBRINSTRUMENTGEN3_POSTPROCESSING_AGGREGATE_MEAN,
    /** standard deviation of the bin */
    RBRINSTRUMENTGEN3_POSTPROCESSING_AGGREGATE_STD,
    /** number of samples in the bin */
    RBRINSTRUMENTGEN3_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT,
    /** The number of specific post-processing aggregate functions. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_AGGREGATE_COUNT,
    /** An unknown or unrecognized post-processing aggregate function. */
    RBRINSTRUMENTGEN3_UNKNOWN_POSTPROCESSING_AGGREGATE
} RBRInstrumentGen3PostprocessingAggregate;

/**
 * \brief Get a human-readable string name for an aggregate function.
 *
 * For consistency with the instrument command language, returns “count”, not
 * “sample count”, for #RBRINSTRUMENTGEN3_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT.
 * The value name only includes `_SAMPLE` to disambiguate between the aggregate
 * function and the value which is the count of valid values,
 * #RBRINSTRUMENTGEN3_POSTPROCESSING_AGGREGATE_COUNT.
 *
 * \param [in] function the aggregate function
 * \return a string name for the aggregate function
 * \see RBRInstrumentGen3Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen3PostprocessingAggregate_name(
    RBRInstrumentGen3PostprocessingAggregate function);

/**
 * Post-processing channel configurations.
 *
 * \see RBRInstrumentGen3Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef struct RBRInstrumentGen3PostprocessingChannelsList
{
    /** \brief The number of channels generated by post-processing. */
    int32_t count;
    /** \brief The definitions of post-processing channels. */
    struct
    {
        /** \brief The function used to aggregate values within bins. */
        RBRInstrumentGen3PostprocessingAggregate function;
        /** \brief The label of the channel to aggregate. */
        char label[RBRINSTRUMENTGEN3_CHANNEL_LABEL_MAX + 1];
    } channels[RBRINSTRUMENTGEN3_POSTPROCESSING_CHANNEL_MAX];
} RBRInstrumentGen3PostprocessingChannelsList;

/**
 * \brief Post-processing job statuses.
 *
 * \see RBRInstrumentGen3Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen3PostprocessingStatus
{
    /** Post-processing is idle. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_STATUS_IDLE,
    /** Post-processing is in progress. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_STATUS_PROCESSING,
    /** Post-processing has completed. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_STATUS_COMPLETED,
    /** Post-processing has been aborted. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_STATUS_ABORTED,
    /** The number of specific post-processing statuses. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_STATUS_COUNT,
    /** An unknown or unrecognized post-processing status. */
    RBRINSTRUMENTGEN3_UNKNOWN_POSTPROCESSING_STATUS
} RBRInstrumentGen3PostprocessingStatus;

/**
 * \brief Get a human-readable string name for a post-processing status.
 *
 * \param [in] status the post-processing status
 * \return a string name for the post-processing status
 * \see RBRInstrumentGen3Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen3PostprocessingStatus_name(
    RBRInstrumentGen3PostprocessingStatus status);

/**
 * \brief Post-processing control commands.
 *
 * \see RBRInstrumentGen3Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen3PostprocessingCommand
{
    /** Start the post-processing job. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_COMMAND_START,
    /** Reset the post-processing job. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_COMMAND_RESET,
    /** Abort any current post-processing job. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_COMMAND_ABORT,
    /** The number of specific post-processing commands. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_COMMAND_COUNT,
    /** An unknown or unrecognized post-processing command. */
    RBRINSTRUMENTGEN3_UNKNOWN_POSTPROCESSING_COMMAND
} RBRInstrumentGen3PostprocessingCommand;

/**
 * \brief Get a human-readable string name for a post-processing command.
 *
 * \param [in] command the post-processing command
 * \return a string name for the post-processing command
 * \see RBRInstrumentGen3Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen3PostprocessingCommand_name(
    RBRInstrumentGen3PostprocessingCommand command);

/**
 * \brief Post-processing bin filters.
 *
 * \see RBRInstrumentGen3Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen3PostprocessingBinFilter
{
    /** No filter. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_BINFILTER_NONE,
    /**
     * \brief Only ascending values.
     *
     * Equivalent to ascending regimes binning. Only valid when binning by
     * depth.
     */
    RBRINSTRUMENTGEN3_POSTPROCESSING_BINFILTER_ASCENTONLY,
    /**
     * \brief Only descending values.
     *
     * Equivalent to descending regimes binning. Only valid when binning by
     * depth.
     */
    RBRINSTRUMENTGEN3_POSTPROCESSING_BINFILTER_DESCENTONLY,
    /** The number of specific post-processing bin filters. */
    RBRINSTRUMENTGEN3_POSTPROCESSING_BINFILTER_COUNT,
    /** An unknown or unrecognized post-processing bin filter. */
    RBRINSTRUMENTGEN3_UNKNOWN_POSTPROCESSING_BINFILTER
} RBRInstrumentGen3PostprocessingBinFilter;

/**
 * \brief Get a human-readable string name for a post-processing bin filter.
 *
 * \param [in] filter the post-processing bin filter
 * \return a string name for the post-processing bin filter
 * \see RBRInstrumentGen3Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen3PostprocessingBinFilter_name(
    RBRInstrumentGen3PostprocessingBinFilter filter);

/**
 * \brief The instrument post-processing configuration.
 *
 * \see RBRInstrumentGen3_getPostprocessing()
 * \see RBRInstrumentGen3_setPostprocessing()
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef struct RBRInstrumentGen3Postprocessing
{
    /**
     * \brief The current state of the instrument's post-processing function.
     *
     * \readonly
     */
    RBRInstrumentGen3PostprocessingStatus status;
    /**
     * \brief Post-processing statistics channel configurations.
     *
     * Functions which receive an RBRInstrumentGen3Postprocessing instance will
     * expect the first RBRInstrumentGen3PostprocessingChannelList.count entries to
     * be populated, and functions which return a RBRInstrumentGen3Postprocessing
     * instance will similarly indicate how many entries are populated.
     */
    RBRInstrumentGen3PostprocessingChannelsList channels;
    /**
     * \brief The reference channel for binning.
     *
     * If the reference is set to the keyword `tstamp`, the generated data will
     * be binned by time. Otherwise, if the reference is set to the channel
     * label of a pressure or sea pressure channel, the generated data is
     * binned by depth.
     */
    char binReference[RBRINSTRUMENTGEN3_CHANNEL_LABEL_MAX + 1];
    /** \brief How data should be filtered before binning. */
    RBRInstrumentGen3PostprocessingBinFilter binFilter;
    /**
     * \brief The size of each bin.
     *
     * When binning by time: specified in milliseconds, with a precision of
     * milliseconds.
     *
     * When binning by depth: specified in decibars, with a minimum precision
     * of 0.1 dbar.
     *
     * The bin size can always be set to 0, in which case, no binning is
     * performed.
     *
     * The bin size may never be negative.
     */
    float binSize;
    /**
     * \brief The minimum timestamp value.
     *
     * All samples with an earlier timestamp are excluded from post-processing
     * input. If time binning is used, this serves as the binning origin point.
     */
    RBRInstrumentGen3DateTime tstampMin;
    /**
     * \brief The maximum timestamp value.
     *
     * All samples with a later timestamp are excluded from post-processing
     * input.
     */
    RBRInstrumentGen3DateTime tstampMax;
    /**
     * \brief The minimum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a lesser depth are excluded from
     * post-processing input; and unless the bin filter is set to
     * #RBRINSTRUMENTGEN3_POSTPROCESSING_BINFILTER_ASCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMin;
    /**
     * \brief The maximum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a greater depth are excluded
     * from post-processing input; and if the bin filter is set to
     * #RBRINSTRUMENTGEN3_POSTPROCESSING_BINFILTER_DESCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMax;
    /**
     * \brief (dynamic correction) Alpha parameter from Lueck and Picklo equation
     *
     * Coefficient is unitless (default 0.08)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcAlpha;
    /**
     * \brief (dynamic correction) Tau parameter from Lueck and Picklo equation (1/beta)
     *
     * Coefficient is unitless (default 8.000)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTau;
    /**
     * \brief (dynamic correction) Parameter for the time lag correction 
     *          between marine temperature and conductivity cell temperature
     *
     * Coefficient is in second (default 0.35)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTdelay;
    /**
     * \brief (dynamic correction) Parameter for the long term thermal coefficient
     *                  for the conductivity cell
     *
     * Coefficient is in 1/celcius (default 2.4e-4)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcCtCoeff;
} RBRInstrumentGen3Postprocessing;

/**
 * \brief Get the instrument post-processing settings.
 *
 * \param [in] instrument the instrument connection
 * \param [out] postprocessing the post-processing parameters
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen3Error RBRInstrumentGen3_getPostprocessing(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3Postprocessing *postprocessing);

/**
 * \brief Set the instrument post-processing settings.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - a post-processing job is already running
 * - you set an out-of-bounds parameter the library fails to detect
 *
 * \param [in] instrument the instrument connection
 * \param [in] postprocessing the post-processing parameters
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully written
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR when the settings cannot be changed
 * \return #RBRINSTRUMENTGEN3_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen3Error RBRInstrumentGen3_setPostprocessing(
    RBRInstrumentGen3 *instrument,
    const RBRInstrumentGen3Postprocessing *postprocessing);

/**
 * \brief Exercises control over the post-processing state.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - post-processing settings are invalid
 * - the wrong memory format is in use
 * - the requested reference channel is unavailable
 *
 * \param [in] instrument the instrument connection
 * \param [in] command the post-processing command
 * \param [out] status the post-processing status after executing the command
 * \return #RBRINSTRUMENTGEN3_SUCCESS when the settings are successfully written
 * \return #RBRINSTRUMENTGEN3_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN3_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN3_HARDWARE_ERROR when the settings cannot be changed
 * \return #RBRINSTRUMENTGEN3_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen3Error RBRInstrumentGen3_setPostprocessingCommand(
    RBRInstrumentGen3 *instrument,
    RBRInstrumentGen3PostprocessingCommand command,
    RBRInstrumentGen3PostprocessingStatus *status);

/**
 * \brief Calculate the 16-bit CRC using the CCITT polynomial f(x)=x^16+x^12+x^5+1
 * feeding bytes into the generator LSB first and using 0xFFFF as a seed value,
 * is then transmitted.
 *
 * \param [in] data the data string used to calculate the CRC
 * \param [in] size the number of characters in the string used to calculate the CRC
 * \return calculated CRC
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
uint16_t calculateCrc(
    const void *data,
    int32_t size);   

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRINSTRUMENTGEN3MEMORY_H */
