/**
 * \file RBRInstrumentGen4Memory.h
 *
 * \brief Instrument commands and structures pertaining to memory and data
 * retrieval.
 *
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval
 *
 * \copyright
 * Copyright (c) 2018 RBR Ltd.
 * Licensed under the Apache License, Version 2.0.
 */

#ifndef LIBRBR_RBRINSTRUMENTGEN4MEMORY_H
#define LIBRBR_RBRINSTRUMENTGEN4MEMORY_H

#include "RBRInstrumentGen4.h"
#include "RBRInstrumentGen4Configuration.h"
#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief The maximum number of channels which can be generated by a
 * post-processing job.
 */
#define RBRINSTRUMENTGEN4_POSTPROCESSING_CHANNEL_MAX 24

/** \brief The maximum number of datasets the library can enumerate. */
#define RBRINSTRUMENTGEN4_DATASET_COUNT_MAX 32

/**
 * \brief Possible storage access modes for the instrument's data memory.
 *
 * \see RBRInstrumentGen4Storage
 */
typedef enum RBRInstrumentGen4StorageAccess
{
    /** The instrument currently has access to its own data memory. */
    RBRINSTRUMENTGEN4_STORAGE_ACCESS_INSTRUMENT,
    /**
     * A USB host currently has access to the instrument's data memory as
     * a mass storage device.
     */
    RBRINSTRUMENTGEN4_STORAGE_ACCESS_USBHOST,
    /** The number of storage access modes. */
    RBRINSTRUMENTGEN4_STORAGE_ACCESS_COUNT,
    /** An unknown or unrecognized storage access mode. */
    RBRINSTRUMENTGEN4_UNKNOWN_STORAGE_ACCESS
} RBRInstrumentGen4StorageAccess;

/**
 * \brief Get a human-readable string name for a storage access mode.
 *
 * \param [in] access the storage access mode
 * \return a string name for the storage access mode
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4StorageAccess_name(
    RBRInstrumentGen4StorageAccess access);

/**
 * \brief Instrument `storage` command parameters.
 *
 * \see RBRInstrumentGen4_getStorage()
 * \see RBRInstrumentGen4_setStorage()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13828279/storage
 */
typedef struct RBRInstrumentGen4Storage
{
    /**
     * \brief The number of bytes used for storage.
     * \readonly
     */
    int64_t used;
    /**
     * \brief The number of bytes still available for storage.
     * \readonly
     */
    int64_t remaining;
    /**
     * \brief The maximum total size of the memory in bytes.
     * \readonly
     */
    int64_t size;
    /** \brief The storage access mode of the instrument's data memory. */
    RBRInstrumentGen4StorageAccess access;
} RBRInstrumentGen4Storage;

/**
 * \brief Get information about the usage and characteristics of data memory.
 *
 * \note Issues the `storage` command.
 *
 * \param [in] instrument the instrument connection
 * \param [out] storage data memory information
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the parameters are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \see RBRInstrumentGen4_setStorage()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13828279/storage
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getStorage(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Storage *storage);

/**
 * \brief Set the instrument storage parameters.
 *
 * Sends `access`, the command's only writable parameter.
 *
 * \note Issues the `storage` command.
 *
 * \param [in] instrument the instrument connection
 * \param [in] storage the storage parameters to write
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the parameters are successfully
 *                                    written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when the storage access
 *                                                    mode is invalid
 * \see RBRInstrumentGen4_getStorage()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13828279/storage
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setStorage(
    RBRInstrumentGen4 *instrument,
    const RBRInstrumentGen4Storage *storage);

/**
 * \brief Possible dataset statuses.
 *
 * \see RBRInstrumentGen4Dataset
 */
typedef enum RBRInstrumentGen4DatasetStatus
{
    /** The dataset is for a deployment currently in progress. */
    RBRINSTRUMENTGEN4_DATASET_STATUS_OPEN,
    /** The dataset is for a deployment that has ended. */
    RBRINSTRUMENTGEN4_DATASET_STATUS_CLOSED,
    /** The number of specific dataset statuses. */
    RBRINSTRUMENTGEN4_DATASET_STATUS_COUNT,
    /** An unknown or unrecognized dataset status. */
    RBRINSTRUMENTGEN4_UNKNOWN_DATASET_STATUS
} RBRInstrumentGen4DatasetStatus;

/**
 * \brief Get a human-readable string name for a dataset status.
 *
 * \param [in] status the dataset status
 * \return a string name for the dataset status
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4DatasetStatus_name(
    RBRInstrumentGen4DatasetStatus status);

/**
 * \brief `dataset <dataset_label>` command parameters.
 *
 * \see RBRInstrumentGen4_getDataset()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
 */
typedef struct RBRInstrumentGen4Dataset
{
    /**
     * \brief The dataset's label.
     *
     * Set by the caller to select the dataset to read.
     */
    char label[RBRINSTRUMENTGEN4_LABEL_NAME_MAX + 1];

    /** \brief Whether the dataset's deployment is still in progress. */
    RBRInstrumentGen4DatasetStatus status;

    /** \brief The number of schedules run by the dataset's deployment. */
    int32_t scheduleCount;

    /**
     * \brief The labels of the schedules run by the dataset's deployment.
     *
     * The instrument reports the schedules as they were when the dataset
     * was started, not as they are presently defined: a label listed here
     * can name a schedule which no longer exists in the schedule pool.
     */
    char scheduleList[RBRINSTRUMENTGEN4_SCHEDULE_COUNT_MAX]
                     [RBRINSTRUMENTGEN4_LABEL_NAME_MAX + 1];

    /** \brief The total memory usage of the dataset in bytes. */
    int64_t byteCount;

    /** \brief The numerical format used for data storage in this dataset. */
    RBRInstrumentGen4DataType dataType;
} RBRInstrumentGen4Dataset;

/**
 * \brief `dataset` command parameters.
 *
 * \see RBRInstrumentGen4_getDatasetPool()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
 */
typedef struct RBRInstrumentGen4DatasetPool
{
    /**
     * \brief The number of datasets stored in the instrument's memory.
     *
     * \warning Use `min(count, RBRINSTRUMENTGEN4_DATASET_COUNT_MAX)` to
     * avoid an out-of-bounds error when accessing #pool if
     * #maxCount > #RBRINSTRUMENTGEN4_DATASET_COUNT_MAX.
     */
    int32_t count;

    /**
     * \brief The maximum number of datasets that the instrument can store
     * in its memory.
     */
    int32_t maxCount;

    /** \brief The pool of datasets. */
    RBRInstrumentGen4Dataset pool[RBRINSTRUMENTGEN4_DATASET_COUNT_MAX];
} RBRInstrumentGen4DatasetPool;

/**
 * \brief Populate the pool of datasets with the labels of the datasets
 * stored in the instrument's memory.
 *
 * Only the labels are populated: read the remaining parameters of a pool
 * entry with RBRInstrumentGen4_getDataset().
 *
 * \note Issues the `dataset` command.
 *
 * \param [in] instrument the instrument connection
 * \param [out] datasetPool the pool of datasets in storage
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the parameters are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \see RBRInstrumentGen4_getDataset()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getDatasetPool(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4DatasetPool *datasetPool);

/**
 * \brief Populate the parameters of a dataset.
 *
 * The caller sets RBRInstrumentGen4Dataset.label to select the dataset.
 *
 * \note Issues the `dataset <dataset_label>` command.
 *
 * \param [in] instrument the instrument connection
 * \param [in,out] dataset the dataset to read, selected by its label
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the parameters are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when the label is empty
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the dataset does not exist
 * \see RBRInstrumentGen4_getDatasetPool()
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/48890208/dataset
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getDataset(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Dataset *dataset);

/** \brief It determines the type of information retrieved for the specific schedule. 
 * There are three keywoards: data|events|meta.
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/dataset
*/
typedef enum RBRInstrumentGen4Block{
    /** Used to report memory usage for sample data. */
    RBRINSTRUMENTGEN4_BLOCK_DATA,
    /** Used to report memory usege for events. */
    RBRINSTRUMENTGEN4_BLOCK_EVENTS,
    /** Used to report this schedule's meory usage for metadata. */
    RBRINSTRUMENTGEN4_BLOCK_META,
    /** The number of specific type of blocks.*/
    RBRINSTRUMENTGEN4_BLOCK_COUNT,
    /** The unknown or unrecognized block. */
    RBRINSTRUMENTGEN4_BLOCK_UNKNOWN
}RBRInstrumentGen4Block;

/** \brief Get a human-readable block name.
 * \param [in] block the block.
 * \return a string name for the block.
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4Block_name(RBRInstrumentGen4Block block);

/** \brief Delete specified dataset in storage.
 * \param [in] instrument the instrument connection.
 * \param [in] dataset the dataset to be deleted.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/datasetPool
*/

RBRInstrumentGen4Error RBRInstrumentGen4_deleteDataset(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Dataset *dataset);

/** \brief Delete all datasetPool in memory.
 * \param [in] instrument the instrument connection.
 * \param [inout] datasetPool the datasetPool.
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/datasetPool
*/
RBRInstrumentGen4Error RBRInstrumentGen4_deleteDatasetAll(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4DatasetPool *datasetPool);

/*****************************************************************************************************************/
/**
 * \brief Functions available to aggregate channel values within bins.
 *
 * \see RBRInstrumentGen4PostprocessingChannel
 * \see https://docs-rbr.atlassian.net/wiki/spaces/GEN4CR/pages/13830106/download
 */
typedef enum RBRInstrumentGen4PostprocessingAggregate
{
    /** average value in the bin */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_MEAN,
    /** standard deviation of the bin */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_STD,
    /** number of samples in the bin */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT,
    /** The number of specific post-processing aggregate functions. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_COUNT,
    /** An unknown or unrecognized post-processing aggregate function. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_AGGREGATE
} RBRInstrumentGen4PostprocessingAggregate;

/**
 * \brief Get a human-readable string name for an aggregate function.
 *
 * For consistency with the instrument command language, returns “count”, not
 * “sample count”, for #RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_SAMPLE_COUNT.
 * The value name only includes `_SAMPLE` to disambiguate between the aggregate
 * function and the value which is the count of valid values,
 * #RBRINSTRUMENTGEN4_POSTPROCESSING_AGGREGATE_COUNT.
 *
 * \param [in] function the aggregate function
 * \return a string name for the aggregate function
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingAggregate_name(
    RBRInstrumentGen4PostprocessingAggregate function);

/**
 * Post-processing channel configurations.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef struct RBRInstrumentGen4PostprocessingChannelList
{
    /** \brief The number of channels generated by post-processing. */
    int32_t count;
    /** \brief The definitions of post-processing channels. */
    struct
    {
        /** \brief The function used to aggregate values within bins. */
        RBRInstrumentGen4PostprocessingAggregate function;
        /** \brief The label of the channel to aggregate. */
        char label[RBRINSTRUMENTGEN4_CHANNEL_LABEL_MAX + 1];
    } channels[RBRINSTRUMENTGEN4_POSTPROCESSING_CHANNEL_MAX];
} RBRInstrumentGen4PostprocessingChannelList;

/**
 * \brief Post-processing job statuses.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen4PostprocessingStatus
{
    /** Post-processing is idle. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_IDLE,
    /** Post-processing is in progress. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_PROCESSING,
    /** Post-processing has completed. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_COMPLETED,
    /** Post-processing has been aborted. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_ABORTED,
    /** The number of specific post-processing statuses. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_STATUS_COUNT,
    /** An unknown or unrecognized post-processing status. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_STATUS
} RBRInstrumentGen4PostprocessingStatus;

/**
 * \brief Get a human-readable string name for a post-processing status.
 *
 * \param [in] status the post-processing status
 * \return a string name for the post-processing status
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingStatus_name(
    RBRInstrumentGen4PostprocessingStatus status);

/**
 * \brief Post-processing control commands.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen4PostprocessingCommand
{
    /** Start the post-processing job. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_START,
    /** Reset the post-processing job. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_RESET,
    /** Abort any current post-processing job. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_ABORT,
    /** The number of specific post-processing commands. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_COMMAND_COUNT,
    /** An unknown or unrecognized post-processing command. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_COMMAND
} RBRInstrumentGen4PostprocessingCommand;

/**
 * \brief Get a human-readable string name for a post-processing command.
 *
 * \param [in] command the post-processing command
 * \return a string name for the post-processing command
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingCommand_name(
    RBRInstrumentGen4PostprocessingCommand command);

/**
 * \brief Post-processing bin filters.
 *
 * \see RBRInstrumentGen4Postprocessing
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef enum RBRInstrumentGen4PostprocessingBinFilter
{
    /** No filter. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_NONE,
    /**
     * \brief Only ascending values.
     *
     * Equivalent to ascending regimes binning. Only valid when binning by
     * depth.
     */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_ASCENTONLY,
    /**
     * \brief Only descending values.
     *
     * Equivalent to descending regimes binning. Only valid when binning by
     * depth.
     */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_DESCENTONLY,
    /** The number of specific post-processing bin filters. */
    RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_COUNT,
    /** An unknown or unrecognized post-processing bin filter. */
    RBRINSTRUMENTGEN4_UNKNOWN_POSTPROCESSING_BINFILTER
} RBRInstrumentGen4PostprocessingBinFilter;

/**
 * \brief Get a human-readable string name for a post-processing bin filter.
 *
 * \param [in] filter the post-processing bin filter
 * \return a string name for the post-processing bin filter
 * \see RBRInstrumentGen4Error_name() for a description of the format of names
 */
const char *RBRInstrumentGen4PostprocessingBinFilter_name(
    RBRInstrumentGen4PostprocessingBinFilter filter);

/**
 * \brief The instrument post-processing configuration.
 *
 * \see RBRInstrumentGen4_getPostprocessing()
 * \see RBRInstrumentGen4_setPostprocessing()
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
typedef struct RBRInstrumentGen4Postprocessing
{
    /**
     * \brief The current state of the instrument's post-processing function.
     *
     * \readonly
     */
    RBRInstrumentGen4PostprocessingStatus status;
    /**
     * \brief Post-processing statistics channel configurations.
     *
     * Functions which receive an RBRInstrumentGen4Postprocessing instance will
     * expect the first RBRInstrumentGen4PostprocessingchannelList.count entries to
     * be populated, and functions which return a RBRInstrumentGen4Postprocessing
     * instance will similarly indicate how many entries are populated.
     */
    RBRInstrumentGen4PostprocessingChannelList channels;
    /**
     * \brief The reference channel for binning.
     *
     * If the reference is set to the keyword `tstamp`, the generated data will
     * be binned by time. Otherwise, if the reference is set to the channel
     * label of a pressure or sea pressure channel, the generated data is
     * binned by depth.
     */
    char binReference[RBRINSTRUMENTGEN4_CHANNEL_LABEL_MAX + 1];
    /** \brief How data should be filtered before binning. */
    RBRInstrumentGen4PostprocessingBinFilter binFilter;
    /**
     * \brief The size of each bin.
     *
     * When binning by time: specified in milliseconds, with a precision of
     * milliseconds.
     *
     * When binning by depth: specified in decibars, with a minimum precision
     * of 0.1 dbar.
     *
     * The bin size can always be set to 0, in which case, no binning is
     * performed.
     *
     * The bin size may never be negative.
     */
    float binSize;
    /**
     * \brief The minimum timestamp value.
     *
     * All samples with an earlier timestamp are excluded from post-processing
     * input. If time binning is used, this serves as the binning origin point.
     */
    RBRInstrumentGen4DateTime tstampMin;
    /**
     * \brief The maximum timestamp value.
     *
     * All samples with a later timestamp are excluded from post-processing
     * input.
     */
    RBRInstrumentGen4DateTime tstampMax;
    /**
     * \brief The minimum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a lesser depth are excluded from
     * post-processing input; and unless the bin filter is set to
     * #RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_ASCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMin;
    /**
     * \brief The maximum depth value.
     *
     * Specified in decibar with a minimum precision of 0.1 dbar.
     *
     * This parameter is ignored when binning by time.
     *
     * When binning by depth, all samples with a greater depth are excluded
     * from post-processing input; and if the bin filter is set to
     * #RBRINSTRUMENTGEN4_POSTPROCESSING_BINFILTER_DESCENTONLY, this serves as the
     * binning origin point.
     */
    float depthMax;
    /**
     * \brief (dynamic correction) Alpha parameter from Lueck and Picklo equation
     *
     * Coefficient is unitless (default 0.08)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcAlpha;
    /**
     * \brief (dynamic correction) Tau parameter from Lueck and Picklo equation (1/beta)
     *
     * Coefficient is unitless (default 8.000)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTau;
    /**
     * \brief (dynamic correction) Parameter for the time lag correction 
     *          between marine temperature and conductivity cell temperature
     *
     * Coefficient is in second (default 0.35)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcTdelay;
    /**
     * \brief (dynamic correction) Parameter for the long term thermal coefficient
     *                  for the conductivity cell
     *
     * Coefficient is in 1/celcius (default 2.4e-4)
     *
     * This parameter is ignored when no dynamic correction channel are selected
     */
    float dcCtCoeff;
} RBRInstrumentGen4Postprocessing;

/**
 * \brief Get the instrument post-processing settings.
 *
 * \param [in] instrument the instrument connection
 * \param [out] postprocessing the post-processing parameters
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully read
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the feature is unavailable
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen4Error RBRInstrumentGen4_getPostprocessing(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4Postprocessing *postprocessing);

/**
 * \brief Set the instrument post-processing settings.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - a post-processing job is already running
 * - you set an out-of-bounds parameter the library fails to detect
 *
 * \param [in] instrument the instrument connection
 * \param [in] postprocessing the post-processing parameters
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the settings cannot be changed
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setPostprocessing(
    RBRInstrumentGen4 *instrument,
    const RBRInstrumentGen4Postprocessing *postprocessing);

/**
 * \brief Exercises control over the post-processing state.
 *
 * Hardware errors may occur if:
 *
 * - post-processing is not available for the instrument
 * - post-processing settings are invalid
 * - the wrong memory format is in use
 * - the requested reference channel is unavailable
 *
 * \param [in] instrument the instrument connection
 * \param [in] command the post-processing command
 * \param [out] status the post-processing status after executing the command
 * \return #RBRINSTRUMENTGEN4_SUCCESS when the settings are successfully written
 * \return #RBRINSTRUMENTGEN4_TIMEOUT when a timeout occurs
 * \return #RBRINSTRUMENTGEN4_CALLBACK_ERROR returned by a callback
 * \return #RBRINSTRUMENTGEN4_HARDWARE_ERROR when the settings cannot be changed
 * \return #RBRINSTRUMENTGEN4_INVALID_PARAMETER_VALUE when parameter values are out
 *                                                of range
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
RBRInstrumentGen4Error RBRInstrumentGen4_setPostprocessingCommand(
    RBRInstrumentGen4 *instrument,
    RBRInstrumentGen4PostprocessingCommand command,
    RBRInstrumentGen4PostprocessingStatus *status);

/**
 * \brief Calculate the 16-bit CRC using the CCITT polynomial f(x)=x^16+x^12+x^5+1
 * feeding bytes into the generator LSB first and using 0xFFFF as a seed value,
 * is then transmitted.
 *
 * \param [in] data the data string used to calculate the CRC
 * \param [in] size the number of characters in the string used to calculate the CRC
 * \return calculated CRC
 * \see https://docs.rbr-global.com/L3commandreference/commands/memory-and-data-retrieval/postprocessing
 */
uint16_t calculateCrcGen4(
    const void *data,
    int32_t size);   

#ifdef __cplusplus
}
#endif

#endif /* LIBRBR_RBRINSTRUMENTMEMORY_H */
