#! /bin/sh
# Report every library, header, test, and example source whose formatting differs
# from what clang-format produces from the repository's .clang-format.
status=0
for f in src/*.c src/*.h include/*.h testsGen3/*.c testsGen3/*.h \
         examples/posixGen3/*.c examples/posixGen3/*.h \
         examples/posixGen4/*.c examples/posixGen4/*.h \
         examples/zephyrGen3/application/src/*.c examples/zephyrGen3/application/src/*.h \
         examples/dynamicCorrectionGen3/*.c \
         testsGen4/*.c testsGen4/*.h
do
    # The test runners are generated by the Makefile, not sources to format.
    case "$f" in
        testsGen3/tests.c|testsGen4/tests.c) continue ;;
    esac

    if ! clang-format --dry-run --Werror "$f" >/dev/null 2>&1
    then
        echo "$f"
        status=1
    fi
done
exit $status
